import { Router, Request, Response } from 'express';
import { getJettonWallets } from '../toncenter';
import { cache, TTL } from '../cache';
import { resolveOr400 } from '../services/addressContext';
import { EVM_CHAINS, evmGetBalance } from '../services/chains/evm';
import { solanaGetBalance } from '../services/chains/solana';
import { tronGetBalance } from '../services/chains/tron';

const router = Router({ mergeParams: true });

const KNOWN_TOKENS: Array<{ address: string; symbol: string; name: string; decimals: number; chain: string }> = [
  { address: 'EQCbSLtzNR9LHilFECc0OcZBz3ap4zYzU6gR4EC6EZoIzNvu', symbol: '$Blu', name: 'Russian Blue', decimals: 9, chain: 'ton' },
  { address: 'EQB-vc00g9PeUWLptSAH4g1J5kYS7WTgtVEfhI6oKdQtRudE', symbol: '$CLAY', name: 'Clayton', decimals: 9, chain: 'ton' },
  { address: 'EQDBLHXhHVVbIHCQ-5IqThP9TFd-bhCk5uyhclZfKuHTZUuu', symbol: '$DIGGY', name: 'DIGGY', decimals: 9, chain: 'ton' },
  { address: 'EQBa4nrNBX2LtJemhMXxkMPQpmCKNlt536SVleo1TYwcSdP7', symbol: '$MASCOT', name: 'Russia Mascot', decimals: 9, chain: 'ton' },
  { address: 'EQC6KPc3IH2m1CY7Z3Uonqj7azE-R_RQEimEQ-OHVECu7Npe', symbol: '$NOTINU', name: 'NOTCOIN INU', decimals: 9, chain: 'ton' },
  { address: 'EQBwHOvf3UrPPJB7jeDHaOT-2vP0QQlDoEDBsgfv5XF75J3j', symbol: '$RECA', name: 'The Resistance Cat', decimals: 9, chain: 'ton' },
  { address: 'EQB5Wjo7yXdaB70yBoN2YEv8iVPjAdMObf_Dq40ELLaPllNb', symbol: '1RUS', name: 'Ton Miner', decimals: 9, chain: 'ton' },
  { address: 'EQBT2Ee4Lx5w9uI7oMly5upXNs3ABWL_Fwk1uiM74gZCGaYt', symbol: '1RUSD', name: '1RUS DAO', decimals: 9, chain: 'ton' },
  { address: 'EQC1bH4tFR2tEVQuW4i2RwwpccoaSy-GRQEqYrCKgZNfNw0r', symbol: '8num', name: 'Shards of Anonymous Telegram Numbers', decimals: 9, chain: 'ton' },
  { address: 'EQC7rnHHtMVBKyhiGnAbtYIlzGxS0dfi3ZbHExFX0LYi9cAH', symbol: '@BTC25', name: '@BTC25 MEMECOIN TonMiner', decimals: 9, chain: 'ton' },
  { address: 'EQAZWjL_bAemZOLO7txY-dHkp9oSNkQ9GQUDR5rKhL5pX692', symbol: 'A5', name: 'A5', decimals: 9, chain: 'ton' },
  { address: 'EQBIzvHeNGl1CCALgCa_iC-OiK_4lFhs_TBKtRNjP6fi0024', symbol: 'AIC', name: 'AI Coin', decimals: 9, chain: 'ton' },
  { address: 'EQBgCpDJVh1poEQS5ApQ0yg_K_J8SC9pdaMnlwPk7hjVClMQ', symbol: 'AKA', name: 'AKA Liberty', decimals: 9, chain: 'ton' },
  { address: 'EQDPMNvXl3si1TXGXMwnUhwQjE0mMcxHKtYXFSubaicYkeaQ', symbol: 'AKORN', name: 'Akorn Liberty', decimals: 9, chain: 'ton' },
  { address: 'EQAYObSAEunbFFxpJC9OHSm6PMlBNbNns7KvcuRRuEB8bIQI', symbol: 'ALEN', name: 'ALEN', decimals: 9, chain: 'ton' },
  { address: 'EQCYLW2uXyMiCIfQawyp2Fbmk8DqDhMmYje9cINU46IgrEEu', symbol: 'ALENKA', name: 'ALENKA', decimals: 9, chain: 'ton' },
  { address: 'EQD44QL9oawLp3hqLNMRd4HvDK-i4mtm6ZBw2CJ7QOtvSNtf', symbol: 'ALISHER', name: 'Alisher', decimals: 9, chain: 'ton' },
  { address: 'EQAlKuU3JVwD1BcsSqLfigW75kbtPxnpo6Uur4GjBvSfgTTD', symbol: 'ALIVE', name: 'AliveBoard', decimals: 9, chain: 'ton' },
  { address: 'EQDlnVo-6abJzyHlU8uB7pRjE7OIKt4HTTDPG4hfwOf5jTPg', symbol: 'ALL', name: 'ALL', decimals: 9, chain: 'ton' },
  { address: 'EQDs4_MWmRySmPbsW6MyZ8Dy-k-Bi0vZNNSVt6LE2LC_ddUP', symbol: 'ALT', name: 'AltOOshka', decimals: 9, chain: 'ton' },
  { address: 'EQDN7LXx6C4TWB4qMoe1Z5O114rPw9Jar2-oOhWXRvrc4Nh3', symbol: 'ALWIN', name: 'ALWIN AirDrop', decimals: 9, chain: 'ton' },
  { address: 'EQBv2cEJ-T-1GNRdzaY_JYoJvpAISuFHOKmJZPQnoUqEHTlU', symbol: 'AMBER', name: 'AmberTON', decimals: 9, chain: 'ton' },
  { address: 'EQCcLAW537KnRg_aSPrnQJoyYjOZkzqYp6FVmRUvN1crSazV', symbol: 'AMBR', name: 'Ambra', decimals: 9, chain: 'ton' },
  { address: 'EQC7js8NLX3v57ZuRmuusNtMSBdki4va_qyL7sAwdmosf_xK', symbol: 'AMORE', name: 'Amocucinare', decimals: 9, chain: 'ton' },
  { address: 'EQDhnXQgjkymx2DgbcLZqvLClyBEsFAAr-RotkrXhf1OD3Gp', symbol: 'ANDY', name: 'Andy', decimals: 9, chain: 'ton' },
  { address: 'EQDv-yr41_CZ2urg2gfegVfa44PDPjIK9F-MilEDKDUIhlwZ', symbol: 'ANON', name: 'ANON', decimals: 9, chain: 'ton' },
  { address: 'EQAzBy-W8GJjUPfU-8eV0Jz56Jc5dIvvP-qznHKQhlqzGkoZ', symbol: 'APC', name: 'AIYA PowerCell', decimals: 9, chain: 'ton' },
  { address: 'EQDFu29cK35aAPEHcZRfeC0QqoeY1UdfVpsjO_kjVS3VLF_P', symbol: 'APHBT', name: 'AiPhABeT', decimals: 9, chain: 'ton' },
  { address: 'EQAM2KWDp9lN0YvxvfSbI0ryjBXwM70rakpNIHbuETatRWA1', symbol: 'ARBUZ', name: 'ARBUZ', decimals: 9, chain: 'ton' },
  { address: 'EQBMxFekc39SONbY8Mes8IwnZZlsPzeZhwz2c7sqMkkjI0uy', symbol: 'ATC', name: 'AutoTCrypto', decimals: 9, chain: 'ton' },
  { address: 'EQCpkuD6gpAdXWJDOLKyxx6ngDDcXz2AS85jWyDWa3qTVXYQ', symbol: 'AUM', name: 'YOGAFERMA', decimals: 9, chain: 'ton' },
  { address: 'EQDtrpq6zmwzfqFL9JWnXzjZoZhK9xaprFCXerxPS4ZbS5tl', symbol: 'AUR', name: 'Aurum', decimals: 9, chain: 'ton' },
  { address: 'EQAC7ARsJ6ScpxGXPKK3-w2hXvGiDTfE9wlxN02HmaLtKhvw', symbol: 'AVTR', name: 'VZGLYAD AVTORA', decimals: 9, chain: 'ton' },
  { address: 'EQCj2tbgoppYqw7t_CLcj3nZnRhODIQDlcHvJpD7jl0jokNT', symbol: 'AZURE', name: 'Azure', decimals: 18, chain: 'ton' },
  { address: 'EQAWDyxARSl3ol2G1RMLMwepr3v6Ter5ls3jiAlheKshgg0K', symbol: 'AquaUSD', name: 'AquaUSD', decimals: 6, chain: 'ton' },
  { address: 'EQDgyXtVBaUTYrNIYEyVTOIUCWItOPlj5eViJH7URrFI8DDR', symbol: 'BANANA', name: 'BANANA', decimals: 9, chain: 'ton' },
  { address: 'EQBiHSLVzoicc-LQPDXJc_rF-WRft0aFihccFduA6fQ1ynYM', symbol: 'BARO', name: 'Baron', decimals: 9, chain: 'ton' },
  { address: 'EQDxRD-NX0xtsu2id0tufZLdxBNoiKkzjAQqBh65Zxq2IK48', symbol: 'BBNOT', name: 'Baby Notcoin', decimals: 9, chain: 'ton' },
  { address: 'EQCgH_F0Mf_CENOMPFAsBsqF_Baj8ZkbpSQ5N6lRgfRdlKIj', symbol: 'BC', name: 'Block Card', decimals: 9, chain: 'ton' },
  { address: 'EQAtYvRdPym_VP43JCThafzThjGz8OVbGny_wTWaael671Uq', symbol: 'BCLUB', name: 'Boys Club', decimals: 9, chain: 'ton' },
  { address: 'EQClyeWq9hiaPJRxtKRZhBNrznGNiDouXZy5TWs1QQ2DoiHn', symbol: 'BCOIN', name: 'Bomb Crypto', decimals: 9, chain: 'ton' },
  { address: 'EQCRU1SC3xNf_r33q8NZzLughmvdE21JRYIZj4oRKUdRKRDb', symbol: 'BEE', name: 'BEETON', decimals: 9, chain: 'ton' },
  { address: 'EQAik8dthQ2NheRlkvnCRJPuDcmGmitTeZEL9dNkKfQyffjo', symbol: 'BEN', name: 'BEN', decimals: 9, chain: 'ton' },
  { address: 'EQB_K9TMS9jlY1FTUfW3hpBCedqYsMd-gcjbWokwe35tCWYW', symbol: 'BER', name: 'BER THE BEAR', decimals: 9, chain: 'ton' },
  { address: 'EQCnlkmHz5ySlVLfeUqzPk6pajw5vdU48JzL6SgvAs-vhmSR', symbol: 'BLUPE', name: 'BLUPE', decimals: 9, chain: 'ton' },
  { address: 'EQBm8UOthRHMGr6rCsNRNVwFArYHcWOgw6pAj4JZ2RiQ-yI1', symbol: 'BMW', name: 'Bayerische Motoren Werke AG Coin', decimals: 9, chain: 'ton' },
  { address: 'EQBTjR1nGlxTdRZGSSHeXYvckDkZc3eDwupzBFhz5cDx-eub', symbol: 'BOLGUR', name: 'Airina Bolgur', decimals: 9, chain: 'ton' },
  { address: 'EQD0vdSA_NedR9uvbgN9EikRX-suesDxGeFg69XQMavfLqIw', symbol: 'BOLT', name: 'Huebel Bolt', decimals: 9, chain: 'ton' },
  { address: 'EQA7MaApnfmQLHWCC7eJ6WuUzJ6juMtopwZnLwNaAL7f35Ew', symbol: 'BONES', name: 'Bonescoin', decimals: 9, chain: 'ton' },
  { address: 'EQCavQv8vsZ1waQnqz3lmGEw2HkUM2clUrzjJotwpwzrgcx4', symbol: 'BOOBA', name: 'BOOBA Coin', decimals: 9, chain: 'ton' },
  { address: 'EQCpFonMFFLBC3cJSomCPWnVJjzyxSEA91UIsznHscbfxZwX', symbol: 'BOOM', name: 'Boom', decimals: 9, chain: 'ton' },
  { address: 'EQC_Br9_cFIywrKoAGR3C5EBnrMrWueU0zqQ-0OsldqoADyW', symbol: 'BORIS', name: 'BORIS', decimals: 9, chain: 'ton' },
  { address: 'EQDxl-eii6VYQEIJM0E2CNp1ShbGp8AWp--Yfyk2lRZhvut2', symbol: 'BOS', name: 'Bos Pump', decimals: 9, chain: 'ton' },
  { address: 'EQBglZnD5nClIC3Qhqyss6Mn5Tgk9NzKka9MnBpfJWXye9p4', symbol: 'BOT', name: 'Botfather', decimals: 9, chain: 'ton' },
  { address: 'EQAnmanJNfO07EHZAsHode4AyxCFboiobF1-Y04Q7UG9sinZ', symbol: 'BRETT', name: 'Brett', decimals: 9, chain: 'ton' },
  { address: 'EQC2wH1I9MVQCWvVCNfA85N_TF3tSI50DEE597QNdO66rclf', symbol: 'BROTON', name: 'BROKIE ON TON', decimals: 9, chain: 'ton' },
  { address: 'EQDEM9T1fpCa56C8NKp4e_NuGhdSS-mwiPSvvfksToueZ0IP', symbol: 'BRUSKI', name: 'BRUSKI', decimals: 9, chain: 'ton' },
  { address: 'EQCZkJnhQmcmbAxfzLcfvt6OusqMSYJg-gpy8cI81SjgN9Os', symbol: 'BST', name: 'DeBoost', decimals: 9, chain: 'ton' },
  { address: 'EQCVTnx_n2URo9cuJnOT8FH4z1JcSxGkyXnQpGwR3vEyUeEr', symbol: 'BTCAT', name: 'Baby Ton Cat', decimals: 9, chain: 'ton' },
  { address: 'EQAjjnIVdwE6J0zgDXiXgOU5odFAvDE4iKvYDZx95wK17a8F', symbol: 'BTON', name: 'butTON', decimals: 9, chain: 'ton' },
  { address: 'EQAof8wIlCvwWV6flqnXgTl52O3oOX52pZcFHwmxuyZVfK03', symbol: 'BUCKY', name: 'BUCKY @BuckyBuyBot', decimals: 9, chain: 'ton' },
  { address: 'EQBYnUrIlwBrWqp_rl-VxeSBvTR2VmTfC4ManQ657n_BUILD', symbol: 'BUILD', name: 'BUILD', decimals: 9, chain: 'ton' },
  { address: 'EQDI_QXYeiwrWN85MrOEucZxsmX8XKNsjehOjzk130E0pn1c', symbol: 'BULL', name: 'Bull on TON', decimals: 9, chain: 'ton' },
  { address: 'EQC9zWTrdj7Dm5ZOl1YugX_SSgGcSSeUBivmWToV6joAV-vV', symbol: 'BULL', name: 'Bullish Balloons', decimals: 9, chain: 'ton' },
  { address: 'EQDNJzbNKA8Ix2X7Tv1_jxdCqehPQgJaNbisoIkSq5srnfLs', symbol: 'BURN', name: 'Burncoin', decimals: 9, chain: 'ton' },
  { address: 'EQCWDj49HFInSwSk49eAo476E1YBywLoFuSZ6OO3x7jmP2jn', symbol: 'BabyDoge', name: 'Baby Doge Coin', decimals: 9, chain: 'ton' },
  { address: 'EQBtv7I3pZpMAUChef2Vrk-U1GcCE00rROuHgMJ9CvjodRZW', symbol: 'Bear', name: 'Bear Coin', decimals: 9, chain: 'ton' },
  { address: 'EQA14eTOZEmeS5aQlnze4wWH2STmC062ioyFKIHWGwji_4NH', symbol: 'C4', name: 'C4', decimals: 9, chain: 'ton' },
  { address: 'EQD5cOofGH1LpZbkqxW2iF-VCE5SzKgP1K3ABxdnx6TOg1u1', symbol: 'CARAT', name: 'CARAT', decimals: 9, chain: 'ton' },
  { address: 'EQDIq-S2SqvytT9tv71lhFZ_0rw9OkXLeiAhmhmr3UqJxVow', symbol: 'CASH', name: 'Cash AMA Radio', decimals: 9, chain: 'ton' },
  { address: 'EQBh4XMahI9T81bj2DbAd97ZLQDoHM2rv2U5B59DVZkVN1pl', symbol: 'CATA', name: 'CATA', decimals: 9, chain: 'ton' },
  { address: 'EQD-cvR0Nz6XAyRBvbhz-abTrRC6sI5tvHvvpeQraV9UAAD7', symbol: 'CATI', name: 'Catizen', decimals: 9, chain: 'ton' },
  { address: 'EQCy95IhvMjCGDzvhm5WpqlFXjaPmVYJRWvGtRBcI8B69E3z', symbol: 'CATS', name: 'Cute Cats', decimals: 9, chain: 'ton' },
  { address: 'EQBadq9p12uC1KfSiPCAaoEvhpXPHj7hBWq-mqGntuwE2C1C', symbol: 'CATS', name: 'TON Cats Jetton', decimals: 9, chain: 'ton' },
  { address: 'EQA3AshPEVly8wQ6mZincrKC_CkJSKXqqjyg0VMsVjF_CATS', symbol: 'CATS', name: 'CATS', decimals: 9, chain: 'ton' },
  { address: 'EQD6W0raB1aGCr86pWd7-oWpA3QW2VXCJ9smlYcChkIhflt2', symbol: 'CAVI', name: 'CAVIAR COIN', decimals: 9, chain: 'ton' },
  { address: 'EQBpfD5q4aFgHU17KvNPN_P0QOy41MOIj2TwGX0bbAz44DNs', symbol: 'CCAT', name: 'Communist Cat', decimals: 9, chain: 'ton' },
  { address: 'EQCl0S4xvoeGeFGijTzicSA8j6GiiugmJW5zxQbZTUntre-1', symbol: 'CES', name: 'swap.coffee', decimals: 9, chain: 'ton' },
  { address: 'EQAuDG3Z0V08oad6wQzNK0T1zHbU_HY_6FtemdWsEJ9dHr1M', symbol: 'CHADUROV', name: 'CHADUROV', decimals: 9, chain: 'ton' },
  { address: 'EQBenWCdMBAILriH8yPX9bfmjcZlmer1JgRDHDWblDK13TOp', symbol: 'CHAPA', name: 'ChipiCoin', decimals: 9, chain: 'ton' },
  { address: 'EQCn1L3DFs57RwgQDV9qyaNPJeRckhSn8P9znsck6ePdOl0r', symbol: 'CHMONYA', name: 'ЧМОНЯ', decimals: 9, chain: 'ton' },
  { address: 'EQA2FHorTzvYpsM3t_6IqMuigpJZCB_-5H80CqbIIaULq272', symbol: 'CHORRY', name: 'CHORRY', decimals: 9, chain: 'ton' },
  { address: 'EQC79FqnHGhaqPslE6_1mMIccuGEP7IDGEy2HLcrloG8PE_X', symbol: 'CK', name: 'Crypto Kings', decimals: 9, chain: 'ton' },
  { address: 'EQDUWu9M_5NR812aj5rI3FDBgnVbLyycvj-Fb_u0F__CLOSE', symbol: 'CLOSE', name: 'Closecoin', decimals: 9, chain: 'ton' },
  { address: 'EQA9dayEKflrL-wIf-GKGizj26pvX0QCIxwmRgqzg5U_c3YB', symbol: 'COFE', name: 'Coffee', decimals: 9, chain: 'ton' },
  { address: 'EQCTWKZUR3BlJ-jnT_GE8RtERDOMQ1los7-Up3ipQkTi700i', symbol: 'CPBR', name: 'Capybara', decimals: 9, chain: 'ton' },
  { address: 'EQAdz16aPWCmAYldTiX_g-NRzT-spbN8tCk9dJIHfAiC3L4p', symbol: 'CRDF', name: 'CARDIFY Coin', decimals: 9, chain: 'ton' },
  { address: 'EQB-i1kqPz_MitkRCOzzgDf0_doxahk1bUPVAGjm49zMozOd', symbol: 'CROCO', name: 'Ton Croco', decimals: 6, chain: 'ton' },
  { address: 'EQD36Lxp6p4FMzHQThWzvFNaqhbT8Qip4rMF1NYjCSgY6ksE', symbol: 'CRYPTON', name: 'CRYPTON', decimals: 9, chain: 'ton' },
  { address: 'EQCXSMNX3OB5jPgOJkEzjYhm7FOBfkA3cg7paBqTYwzXrjIi', symbol: 'CUB', name: 'Cubigator', decimals: 9, chain: 'ton' },
  { address: 'EQAnzdfxDYsmUrLTOL7E6ANRWPR-6TlB-LAv-lifsh-55lZF', symbol: 'DANCINGCAT', name: 'Dancing Cat', decimals: 9, chain: 'ton' },
  { address: 'EQBcLHjUJ9Z8LtMRNf-qdqRUVl2mno739oR8IEPDefRR4asj', symbol: 'DBT', name: 'Diamond Bull Technology', decimals: 9, chain: 'ton' },
  { address: 'EQCyWXjgTtVvCMmtcMasvUYTRiBsWxlIKAFT0QJYWjWW2c1W', symbol: 'DD', name: 'DD', decimals: 9, chain: 'ton' },
  { address: 'EQCW5g1evnQN2OZZEVe-23aSvEsgPauWZlF27ZIz5REhnWRy', symbol: 'DDAO', name: 'DEFI HUNTERS DAO', decimals: 9, chain: 'ton' },
  { address: 'EQBTUH6cdozp2TWujAqamNjgmCrXcV7FraQ6KieDu7pYsMjm', symbol: 'DEANON', name: 'DEANON', decimals: 9, chain: 'ton' },
  { address: 'EQA79IISXMR8ve9AOipUE3i5htp6z6I7ynSC9DKBo8zHsIYr', symbol: 'DEER', name: 'MagicDeer', decimals: 9, chain: 'ton' },
  { address: 'EQBc-L5CzzRKmR3-TdOwBm4l-XyJdxJt3HfAIr_qMiKaB7WM', symbol: 'DEPOSIT', name: 'DEPOSIT', decimals: 9, chain: 'ton' },
  { address: 'EQC2BY3fXo2Kn0Yc1MYW9pe8PDx4pT3X87lQJuJmXgnp6R1G', symbol: 'DEX APES CLUB', name: 'DEXAPES', decimals: 9, chain: 'ton' },
  { address: 'EQD26zcd6Cqpz7WyLKVH8x_cD6D7tBrom6hKcycv8L8hV0GP', symbol: 'DFC', name: 'DeFinder Capital', decimals: 9, chain: 'ton' },
  { address: 'EQAaJybAsdcXbeW_PsrQZElZWE4x8mLkL9s58kIc0OtpCWFO', symbol: 'DGN', name: 'TON Degen', decimals: 9, chain: 'ton' },
  { address: 'EQBCFwW8uFUh-amdRmNY9NyeDEaeDYXd9ggJGsicpqVcHq7B', symbol: 'DHD', name: 'DHD Coin', decimals: 9, chain: 'ton' },
  { address: 'EQAOLOJ9jhS1RmzEQwayCcD_8glZhI3m7lNOfoNTUhP4Ta8n', symbol: 'DICK', name: 'adDICKted', decimals: 9, chain: 'ton' },
  { address: 'EQDxE8C4-R53ol4InsjyVedmfI9xMF6lpJko2p90PAR0U5NT', symbol: 'DICKSHOTI', name: 'DICKSHOTI', decimals: 9, chain: 'ton' },
  { address: 'EQCgipn5ILgba4Y99-ZglgN3cI4daWbh6-dxUix5NLpmiEva', symbol: 'DIGFI', name: 'DIGFI', decimals: 9, chain: 'ton' },
  { address: 'EQByLZOaBbpr9EwNonXKEfkkZL1viNsYHezxw5CVK4Bh0zEb', symbol: 'DINJA', name: 'DINJA', decimals: 9, chain: 'ton' },
  { address: 'EQDqZlrARv4jPJpwzbYPNiOtD_CouWxeAGbp7awAzoezQImY', symbol: 'DMT', name: 'Dimethyltryptamine', decimals: 9, chain: 'ton' },
  { address: 'EQCvxJy4eG8hyHBFsZ7eePxrRsUQSFE_jpptRAYBmcG_DOGS', symbol: 'DOGS', name: 'Dogs', decimals: 9, chain: 'ton' },
  { address: 'EQCQxQWU0ZgbQovVRtrHZUgSUTsj9VbViAj2XANGeC35L2aS', symbol: 'DON', name: 'Don', decimals: 9, chain: 'ton' },
  { address: 'EQCgGUMB_u1Gkrskw2o407Ig8ymQmfkxWuPW2d4INuQoPFJO', symbol: 'DONE', name: 'D-ONE', decimals: 9, chain: 'ton' },
  { address: 'EQBE_P2bKO9dHGSwUhZbQv6va-YRuEWUEZuCv_iEXgO-psTz', symbol: 'DRA', name: 'Dracoin', decimals: 9, chain: 'ton' },
  { address: 'EQAZzvY6tSq2IghR8S3mXgc387Wl6yX54MVQdnFJ2EHQ94CB', symbol: 'DRAGO', name: '🔴🟢Triggered DRAGO', decimals: 9, chain: 'ton' },
  { address: 'EQBtxrZtkwaU2gmUiDirYGcjDeLsoVh4u_blG0KdNLboQxVv', symbol: 'DRAGON', name: 'DragonTON', decimals: 9, chain: 'ton' },
  { address: 'EQAhRC_oZ4B9VgMltfNkENSdLktlMADPE73zIiIcL6es2o7-', symbol: 'DRIFT', name: 'TON Drift', decimals: 10, chain: 'ton' },
  { address: 'EQBWORpXsQAtEnVl5TAmEXmkPD8VTwjL8QWjWFjqEHqs3Xei', symbol: 'DRTS', name: 'Darts Coin', decimals: 9, chain: 'ton' },
  { address: 'EQCCSdlx31KvjbsW-rHdgsLSLUdrj64aZI5DTBBHMeZIVulP', symbol: 'DTRUMP', name: 'DONALDTRUMP', decimals: 9, chain: 'ton' },
  { address: 'EQBhRoPmOImcU2e3CLKD6eCZ_PfOz2iYFcOY3139HUUx0phP', symbol: 'DUBAI', name: 'Dubai #2049', decimals: 9, chain: 'ton' },
  { address: 'EQBTcytZjdZwFLj6TO7CeGvn4aMmqXvbX-nODiApbd011gT3', symbol: 'DUCK', name: 'Duck Coin', decimals: 9, chain: 'ton' },
  { address: 'EQB22u_EPF5DyqtZRhjJ2YiZliN-w5ZCq6F_PY6Ia6bvi3Et', symbol: 'DUROV', name: 'Pavel Durov', decimals: 9, chain: 'ton' },
  { address: 'EQBlqsm144Dq6SjbPI4jjZvA1hqTIP3CvHovbIfW_t-SCALE', symbol: 'DUST', name: 'DeDust', decimals: 9, chain: 'ton' },
  { address: 'EQCQZpelevHNsbw5IUtwSa4Cs8kqWww0KsYeDri9kwS18eCz', symbol: 'DYOR', name: 'DYOR Coin', decimals: 15, chain: 'ton' },
  { address: 'EQB2ho8cuNzitlhg_H29pOHUxRD-VlxvIbN0ZVORNh8REGre', symbol: 'Donut', name: 'Donut The Dog', decimals: 6, chain: 'ton' },
  { address: 'EQDNlNA2NSbWtigW37WX__FIu4Y2NNPwijJd3Ktmhi7gdCyv', symbol: 'E4', name: 'E4', decimals: 9, chain: 'ton' },
  { address: 'EQDE2iOVhvteBA8bCxywcmCOPVxJGltPhft8RYDTXiv4lmvM', symbol: 'EAT', name: 'Engage ADS on Ton Open Network', decimals: 9, chain: 'ton' },
  { address: 'EQDc_nrm5oOVCVQM8GRJ5q_hr1jgpNQjsGkIGE-uztt26_Ep', symbol: 'ECOR', name: 'Ecorpay', decimals: 9, chain: 'ton' },
  { address: 'EQDCAjHxgyScUPS-Am_2nAH7C5XWM4fc2X9dVyWpFgHXG2rT', symbol: 'EGG', name: 'EggsWisdom', decimals: 9, chain: 'ton' },
  { address: 'EQCdb8hvMDDZcqpPGH-cCj3iMuom9P57mMyrdoHNNyXHM9Fs', symbol: 'ESIM', name: 'EvoSimGame', decimals: 6, chain: 'ton' },
  { address: 'EQD6fdBx0HP13JfcVocPgQCjKqpKXh3hXSMVGVHe5yRA1fb_', symbol: 'FAST', name: 'Fast UP', decimals: 5, chain: 'ton' },
  { address: 'EQCsN1IslttnFpGjUabpt3RCnVYca74ZB9yD0L2ZK9CvJ53D', symbol: 'FID', name: 'Ferma Invest Dom', decimals: 3, chain: 'ton' },
  { address: 'EQATcUc69sGSCCMSadsVUKdGwM1BMKS-HKCWGPk60xZGgwsK', symbol: 'FISH', name: 'TON FISH MEMECOIN', decimals: 9, chain: 'ton' },
  { address: 'EQA4YM9cFn4swQUfF9BgUFb7UDYs7hfWG9rMhXUn6Wp1G0Kx', symbol: 'FKMORGEN', name: 'FUCK MORGENSHTERN', decimals: 9, chain: 'ton' },
  { address: 'EQAcSYrcJrqeOtw6CmK1_kkTx7YsP6Or8pvGBQrAFYZbCQxQ', symbol: 'FLIP', name: 'Coin Flipper', decimals: 9, chain: 'ton' },
  { address: 'EQARmDybfEvyI_r3JW7zZAV-VTz8pWvseuIWpjYqQA44ui9r', symbol: 'FLOKIT', name: 'FlokiTon', decimals: 9, chain: 'ton' },
  { address: 'EQDg5ZUYobXbQkDbKCJKDnpAd9BKhdI7swVJdyfZh_LXvrfl', symbol: 'FLOX', name: 'FLOX', decimals: 9, chain: 'ton' },
  { address: 'EQCe_XrSfg4MnL3-ro1akAEWxdfHiXMd24_XgTJhrioCek9R', symbol: 'FLY', name: 'FLYKI Token', decimals: 9, chain: 'ton' },
  { address: 'EQDCJL0iQHofcBBvFBHdVG233Ri2V4kCNFgfRT-gqAd3Oc86', symbol: 'FNZ', name: 'Fanzee Token', decimals: 9, chain: 'ton' },
  { address: 'EQDRh0VZoEWXHtpUi8NKagNlIfJYxssa5yelf7UWML3y3RC2', symbol: 'FOMO', name: 'TONFOMO', decimals: 9, chain: 'ton' },
  { address: 'EQD0KpcRMh-sKO2z5-vOjgvFjTT58tO-2Nmvxqg5ocFQFtWz', symbol: 'FPIBANK', name: 'FPIBANK', decimals: 9, chain: 'ton' },
  { address: 'EQASw-4YMyp3HDLLTgjDlU1EB9d1R5cKgVzUPQbizHWABz6U', symbol: 'FRE', name: 'FRANC', decimals: 9, chain: 'ton' },
  { address: 'EQAzCdBIJdZZnpfn4h7t7AOk5E7MAaxUsIRABuolViGZrhzI', symbol: 'FROG', name: 'Leagushka', decimals: 9, chain: 'ton' },
  { address: 'EQD6ixDKV3pegpJu2758s62OrwXk00ml71wn7o5uzHU19BPt', symbol: 'FROGS', name: 'FROGS', decimals: 9, chain: 'ton' },
  { address: 'EQAA8LaTXHBojqCA5nVHz9-MBoHTw1l3Ordeuy_Z7yGrxocS', symbol: 'FROGY', name: 'Frogy LIVE', decimals: 9, chain: 'ton' },
  { address: 'EQDCBwiUEeeBLHhqIW161yObGvO7_BqZeD3XR5E2y_fwfiMG', symbol: 'FTON', name: 'Fanton', decimals: 9, chain: 'ton' },
  { address: 'EQCh9DUkmEdz7BuM_kv_iDqXeXWHrMUZHcZfXnr8yBAfPHcn', symbol: 'FWT', name: 'FadeWallet Token', decimals: 9, chain: 'ton' },
  { address: 'EQB8uhcKPm9IavIEzonGkPG85aIIXPonr5yPSesaXRnVU2JJ', symbol: 'GAS000', name: 'GAS000', decimals: 9, chain: 'ton' },
  { address: 'EQB8O0JJ-hqeDAqDC1OG6zPYBfpV-QzwPed0kpcbILXsmAxG', symbol: 'GEM', name: 'Gem', decimals: 9, chain: 'ton' },
  { address: 'EQA1cdXEKWrt-I2U7MV1hJ8FpduwJu6CydoioAYtOr921wyg', symbol: 'GEM', name: 'NotBlumHmstrCatiDogsWoof', decimals: 9, chain: 'ton' },
  { address: 'EQBX6K9aXVl3nXINCyPPL86C4ONVmQ8vK360u6dykFKXpHCa', symbol: 'GEMSTON', name: 'GEMSTON', decimals: 9, chain: 'ton' },
  { address: 'EQAtyIuO-2x0bp_imQhyOHVT5-Xx8K8tdqsGkED-BME9urj_', symbol: 'GG', name: '⛽️GasGod', decimals: 9, chain: 'ton' },
  { address: 'EQC9nbBFGmL-PXyq2S8qQMOAhZPuxjf3sfRIfUtukqRPXo0o', symbol: 'GG', name: 'GoodGame', decimals: 9, chain: 'ton' },
  { address: 'EQDWSm618mrf84PUjlu8rAMnlTa3RGhMzWb-UadvB5vLyqCv', symbol: 'GGAI', name: 'Gaileo', decimals: 9, chain: 'ton' },
  { address: 'EQD0nt2W1YwJFdMQ-GIx4jguNbvbjS-aM32jOW7hTQs58lds', symbol: 'GGT', name: 'Grabscape governance token', decimals: 9, chain: 'ton' },
  { address: 'EQCBdxpECfEPH2wUxi1a6QiOkSf-5qDjUWqLCUuKtD-GLINT', symbol: 'GLINT', name: 'Glint Coin', decimals: 9, chain: 'ton' },
  { address: 'EQCwaOWpWvxlh--VaCJSkf8I5xEmuCXKKkXuGM3P9PAkJclJ', symbol: 'GLITCH', name: 'GLITCH', decimals: 9, chain: 'ton' },
  { address: 'EQB9e2RJaJnX_tALDBSyIb5oj0YHJLa8FncsF-5MjXolbUzC', symbol: 'GM', name: 'GM', decimals: 9, chain: 'ton' },
  { address: 'EQBCoynGYslAMjv_gRl_2_B1KMOvh9ZW-ae0p7SaXZy6KFjY', symbol: 'GOI', name: 'GoiCoin 2', decimals: 9, chain: 'ton' },
  { address: 'EQD0laik0FgHV8aNfRhebi8GDG2rpDyKGXem0MBfya_Ew1-8', symbol: 'GOMINING', name: 'GoMining', decimals: 18, chain: 'ton' },
  { address: 'EQBlWgKnh_qbFYTXfKgGAQPxkxFsArDOSr9nlARSzydpNPwA', symbol: 'GOVNO', name: 'GOVNO', decimals: 9, chain: 'ton' },
  { address: 'EQAmXCLQN6PcgKMhK91_bAPqbSvyiCw4eZRAIStkSi7fUaRA', symbol: 'GOY', name: 'Goy Token', decimals: 9, chain: 'ton' },
  { address: 'EQB2ONl9nfzoGfeRFhvKTLX28MOD_nvT8cfI41-FylvNvvHm', symbol: 'GPTON', name: 'GPTON', decimals: 6, chain: 'ton' },
  { address: 'EQCILWMtTu_ShFu0WPZnZx9SfCX70dTypBESubKMZUPQOd53', symbol: 'GPU', name: 'GPU — M2M coin', decimals: 9, chain: 'ton' },
  { address: 'EQC47093oX5Xhb0xuk2lCr2RhS8rj-vul61u4W2UH5ORmG_O', symbol: 'GRAM', name: 'Gram', decimals: 9, chain: 'ton' },
  { address: 'EQBj7uoIVsngmS-ayOz1nHENjZkjTt5mXB4uGa83hmcqq2wA', symbol: 'GRBS', name: 'Grabscape game token', decimals: 9, chain: 'ton' },
  { address: 'EQAu7qxfVgMg0tpnosBpARYOG--W1EUuX_5H_vOQtTVuHnrn', symbol: 'GRC', name: 'Grouche coin', decimals: 9, chain: 'ton' },
  { address: 'EQAj680BapntDEm6parX4BfX_S1Jcb1qpF63BREiHZYBGENE', symbol: 'GTON', name: 'Gatto', decimals: 9, chain: 'ton' },
  { address: 'EQBhKT4-OaSZaxBBcvDE4u8s3L1v8u_6cHxSJQWcztld6AFt', symbol: 'GWT', name: 'Goblin World Token', decimals: 9, chain: 'ton' },
  { address: 'EQB8FQKkLgVEMqftUBA7m1OSas38-B8Ea_cWrvsEpMM-4TG1', symbol: 'Gena', name: 'Крокодил Гена', decimals: 9, chain: 'ton' },
  { address: 'EQBFq7ccF0eSWly0yFJwlq4hguBaGVVD4lsHEbCCHashcaSH', symbol: 'HASHCASH', name: 'Hashcash', decimals: 9, chain: 'ton' },
  { address: 'EQCN2dkvaosVjpa9XozzN0wm1MBcI2GTN71CWvRzIsSH7IRH', symbol: 'HDCN', name: 'Headcoin', decimals: 9, chain: 'ton' },
  { address: 'EQCLWvCj44QYTeLujnCYKH7DoAuk_O7QI-LnAt3X5bOfNFMy', symbol: 'HIF', name: 'Hedgehog in the fog', decimals: 9, chain: 'ton' },
  { address: 'EQAJ8uWd7EBqsmpSWaRdf_I-8R8-XHwh3gsNKhy-UrdrPcUo', symbol: 'HMSTR', name: 'Hamster Kombat', decimals: 9, chain: 'ton' },
  { address: 'EQAWVv2x6txoc5Nel9CltbfYSBMOOf0R9sb7GnqY-4ncmjcQ', symbol: 'HOLY', name: 'Holy Coin', decimals: 9, chain: 'ton' },
  { address: 'EQBGuLORB7CME5XR9cdoxazRMFXfVc3H8HZLzq6x1BXKbTk-', symbol: 'HOOT', name: 'Hootcoin', decimals: 9, chain: 'ton' },
  { address: 'EQDQEUr0LPi8m6D6F0Wrvuok7tZbAcr0yn2Y7hK291MMzMjM', symbol: 'HPO', name: 'Hipo Governance Token', decimals: 9, chain: 'ton' },
  { address: 'EQD4P32U10snNoIavoq6cYPTQR82ewAjO20epigrWRAup54_', symbol: 'HYDRA', name: 'Hydra', decimals: 6, chain: 'ton' },
  { address: 'EQApa0Z5I0lMeitSTUtytce5Z5y4Yak5jBwS8Cw53P1Davtw', symbol: 'Hasbik', name: 'Hasbulla', decimals: 9, chain: 'ton' },
  { address: 'EQCtnNdPnA4NTt4XQ_M21dKyoUR7da_SX7uqtO-wh1HeqsX4', symbol: 'ICTN', name: 'indicaTon', decimals: 9, chain: 'ton' },
  { address: 'EQDfefbhN-qmZqH5UZgFQ7GrrRex6ALMgPFImfADHwwDblj6', symbol: 'IF', name: 'IF', decimals: 9, chain: 'ton' },
  { address: 'EQDMA7MRsLj_A6bzX4VEw76x-3LBInipMS9RGdcsmnxFN6CG', symbol: 'IFT', name: 'Informatoken', decimals: 9, chain: 'ton' },
  { address: 'EQBlHnYC0Uk13_WBK4PN-qjB2TiiXixYDTe7EjX17-IV-0eF', symbol: 'INC', name: 'Ton Invaders Coin', decimals: 9, chain: 'ton' },
  { address: 'EQACGPrFHWCy9QmeFXPqvZflyoeBb5grVQxAaucF0hNd1sEs', symbol: 'IVS', name: 'Stalin', decimals: 9, chain: 'ton' },
  { address: 'EQDByR6xbRrTWIQFKfeBIjkIWLvnrlenGV97kiV3sEXRpT8E', symbol: 'JACK', name: 'Outback Jack', decimals: 9, chain: 'ton' },
  { address: 'EQAvvEdq4x5K6owjsMI4X6AxKkTBXVKIVkiSHDLt6i2LFnnQ', symbol: 'JBCT', name: 'Bear Country Token', decimals: 9, chain: 'ton' },
  { address: 'EQANARUwOrJR3whiESWVuQTnKjm7EoUKcO1DQkRkRzUj6nib', symbol: 'JETTON', name: 'Jetty', decimals: 9, chain: 'ton' },
  { address: 'EQAQXlWJvGbbFfE8F3oS8s87lIgdovS455IsWFaRdmJetTon', symbol: 'JETTON', name: 'JetTon', decimals: 9, chain: 'ton' },
  { address: 'EQAejag_GBPBdSpVZGcWrSQuZmDQxaYJCsHzB0RQTeyEa0Nh', symbol: 'JMT', name: 'JETMOON', decimals: 9, chain: 'ton' },
  { address: 'EQBFU3EK91HdX7opot3I2Cpd3K0chOMrycDfUtVftYjN4_m2', symbol: 'JRK', name: 'Jirinovskiy Coin', decimals: 3, chain: 'ton' },
  { address: 'EQC8FoZMlBcZhZ6Pr9sHGyHzkFv9y2B5X9tN61RvucLRzFZz', symbol: 'JVT', name: 'JVault Token', decimals: 9, chain: 'ton' },
  { address: 'EQCbyLthlECDjjq8KFRHCz9Up3Hv7917lP4AiI9KGqccoSFK', symbol: 'KAIF', name: 'Kaif', decimals: 9, chain: 'ton' },
  { address: 'EQDqz7LTwgj016kiTiSooM_ft8kveL2P4pj4fkJmsUV_an_X', symbol: 'KAKAXA', name: 'KAKAXA', decimals: 9, chain: 'ton' },
  { address: 'EQDXLBzdtWb47zCy_-TnVASDa7kxAP7_A6G_UGt7lQEbGD_5', symbol: 'KGO', name: 'Kasongo Coin', decimals: 9, chain: 'ton' },
  { address: 'EQC-tdRjjoYMz3MXKW4pj95bNZgvRyWwZ23Jix3ph7guvHxJ', symbol: 'KINGY', name: 'KINGYTON', decimals: 9, chain: 'ton' },
  { address: 'EQCSLLVQ8qdhEqZUKaiKU7F6sVfnNPmQ4FsCpCo8olo795LP', symbol: 'KITO', name: 'Kito', decimals: 9, chain: 'ton' },
  { address: 'EQAmLDfD9kc5nrqCfrCRQ1pK3KL6wB7Ya4Nud5HjNbwnbiWF', symbol: 'KITSU', name: 'KITSU', decimals: 9, chain: 'ton' },
  { address: 'EQD-LW9jU2btSu_clrc-cXJaHJS6LKJ69QMcpLbFFPUxc4Ux', symbol: 'KOT', name: 'Nikolai KOT Durov', decimals: 9, chain: 'ton' },
  { address: 'EQDDlkB2Hiuz5IGaXdumQTqL3--pbx8IfZQqQOHrxK2-KTON', symbol: 'KRDT', name: 'Krediton', decimals: 9, chain: 'ton' },
  { address: 'EQDsjxmRt6uL0wc5PzEQDy-Q5wFOqV5ZP86l3Cy1mLjiqyJE', symbol: 'LABR', name: 'Labrador', decimals: 9, chain: 'ton' },
  { address: 'EQBowEMCNat-oFMWbRhhGBaEVxQO5qhyqei4P74D2xhx-TR6', symbol: 'LADY', name: 'LADY', decimals: 9, chain: 'ton' },
  { address: 'EQDE1iPrP80L17RzkH3YluXsEcn5i-bPFfue259uMKKFE3h0', symbol: 'LAMBO', name: 'LAMBO', decimals: 9, chain: 'ton' },
  { address: 'EQBl3gg6AAdjgjO2ZoNU5Q5EzUIl8XMNZrix8Z5dJmkHUfxI', symbol: 'LAVE', name: 'Lavandos', decimals: 9, chain: 'ton' },
  { address: 'EQBBT7wVw95n16wTzOzTWlYqcjh2z0jY-1qm8dep4R4PxGEK', symbol: 'LAZY', name: 'LazyCoin', decimals: 9, chain: 'ton' },
  { address: 'EQA6NZTlZbNx192v0Ndjo6alxIRAiyEqDKqHp5R0UVMw5ANv', symbol: 'LEA', name: 'Alliance', decimals: 9, chain: 'ton' },
  { address: 'EQA4J3o_XTdWLzqZ5cfKdKMzIAo43arw9VfLbC4xolaISkWD', symbol: 'LEDO', name: 'Lego Resistance Dog', decimals: 9, chain: 'ton' },
  { address: 'EQA5-G7djF86kQlspnEu4RI2HN-zgu81DcE_ap0yuA84fa1x', symbol: 'LESHA', name: 'CAT LESHA', decimals: 9, chain: 'ton' },
  { address: 'EQCPju-9JN0fK4BToOvA6aPdByR5CmyrNGqeMhuRz35ZE8C1', symbol: 'LFGO', name: 'Lets Fuckin Go', decimals: 9, chain: 'ton' },
  { address: 'EQD3xWvgIsPEU_U3E393wyCQ1dWKf7MiycwDa8IH6Ant41xo', symbol: 'LIBER', name: 'Libercoin', decimals: 9, chain: 'ton' },
  { address: 'EQD_KpO2-iFeHPT4dF0ur9E0iAFts2fwhpR2KjwAmYKpccvH', symbol: 'LIFEYT', name: 'ЖЮ', decimals: 9, chain: 'ton' },
  { address: 'EQCQ8FSCoOnCIaeX29YFGOgGdRn7p9A1uS8giVjZKQyRDxui', symbol: 'LIQ', name: 'Liquidator', decimals: 9, chain: 'ton' },
  { address: 'EQCyDhcASwIm8-eVVTzMEESYAeQ7ettasfuGXUG1tkDwVJbc', symbol: 'LKY', name: 'Lucky TON', decimals: 8, chain: 'ton' },
  { address: 'EQDJXgXvdkTCG0N6-e6B1-fl1U1LnPHMYpqio3UEA9KAZ07j', symbol: 'LLAMA', name: 'LLAMA', decimals: 9, chain: 'ton' },
  { address: 'EQAZoo9I2LxapciXQQ3D4RJ0JGoCaOE5DUUQdIzIg_Xymtoq', symbol: 'LON', name: 'Luna or Not', decimals: 9, chain: 'ton' },
  { address: 'EQAS2elYb6_hqWyOl7gpuYTzf1sqmjLJQ0lQ4X_4d_MvtMWR', symbol: 'LOVE', name: 'Love You', decimals: 9, chain: 'ton' },
  { address: 'EQBa6Oofc4vQZ1XZLTYRkbX4qWUWBCf0sFBgo0kdxdlw6rqN', symbol: 'M5', name: 'META', decimals: 9, chain: 'ton' },
  { address: 'EQBNZljvUI3OqUayhwHkkzhKtOQj2L0jTjLKX2iJpuf3GItR', symbol: 'MAGIX', name: 'MAGIX', decimals: 6, chain: 'ton' },
  { address: 'EQCuPm01HldiduQ55xaBF_1kaW_WAUy5DHey8suqzU_MAJOR', symbol: 'MAJOR', name: 'Major', decimals: 9, chain: 'ton' },
  { address: 'EQBwomwKbKHoz2WqX7X-ajpynsh88o1EtUicYQikQBY7f635', symbol: 'MANDA', name: 'Mandarin', decimals: 9, chain: 'ton' },
  { address: 'EQB0HOlHAV5l977NTD33zkgzOan4IBBYCvmDLjDf9B1IX3W7', symbol: 'MANDER', name: 'Commander', decimals: 9, chain: 'ton' },
  { address: 'EQBjEw-SOe8yV2kIbGVZGrsPpLTaaoAOE87CGXI2ca4XdzXA', symbol: 'MARGA', name: 'Margaritis', decimals: 9, chain: 'ton' },
  { address: 'EQAL6e1UNPFksn8198qOD6KICnplw6f9cMIFuQW3xV9ld3Ro', symbol: 'MARS', name: 'Mars', decimals: 9, chain: 'ton' },
  { address: 'EQCOe7CdgxUsaWBta4AgRxWtd6D7rzSvI8mwgQPh0VIcLlsn', symbol: 'MASHA', name: 'MASHA', decimals: 9, chain: 'ton' },
  { address: 'EQCbKMTmEAdSnzsK85LOpaDkDH3HjujEbTePMSeirvEaNq-U', symbol: 'MC', name: 'Magic Crystal', decimals: 9, chain: 'ton' },
  { address: 'EQBXbtgIocvb10GQKVnQjZQqx3tXjGjBWZyS8fh2YcHbsAhT', symbol: 'MCL', name: 'MuscleCare', decimals: 9, chain: 'ton' },
  { address: 'EQCivShe-nigManAil8iRxwKsp74cA0q0a00kmPBtLfRHQgB', symbol: 'MCOM', name: 'Mihaylets Community', decimals: 9, chain: 'ton' },
  { address: 'EQAVw-6sK7NJepSjgH1gW60lYEkHYzSmK9pHbXstCClDY4BV', symbol: 'MEH', name: 'meh', decimals: 9, chain: 'ton' },
  { address: 'EQDeXL9S-ApGesQUbBLYi2RGS9UpWfABGAF8jEDh_6XQjOR6', symbol: 'MELON', name: 'Melon', decimals: 9, chain: 'ton' },
  { address: 'EQAWpz2_G0NKxlG2VvgFbgZGPt8Y1qe0cGj-4Yw5BfmYR5iF', symbol: 'MEM', name: 'Not Meme', decimals: 9, chain: 'ton' },
  { address: 'EQDol2oVpmBznAL6vQpF51QW3p0PKV7ag4VEtex8_MeMHASH', symbol: 'MEMHASH', name: 'Memhash', decimals: 9, chain: 'ton' },
  { address: 'EQC_kG29HfgpJRW2RYIApeQI9PPYdzdsleqiarfo00MvSTSs', symbol: 'MEOW', name: 'Meow', decimals: 9, chain: 'ton' },
  { address: 'EQCvCDFaKVqFB4eSM1r2pHHWAU-NjcbU6vDDUUsTQKqIjGa8', symbol: 'MERGE', name: 'Merge Token', decimals: 9, chain: 'ton' },
  { address: 'EQDAPgCBDBb-HsYEa4ooC7xkUcjjAFlQDpdYYvPeq9AVfC7b', symbol: 'MERO', name: 'MERO Mercury Coin', decimals: 9, chain: 'ton' },
  { address: 'EQDhSXj-di6Wo6__Pqd51dHZHel0MQeaegmhCWm-tkwwtem8', symbol: 'MIC', name: 'Microdiving', decimals: 9, chain: 'ton' },
  { address: 'EQBqaQRN6eReJTzZ-8Rw7uzWsc9jv85czdgMzLGa59Jb24vK', symbol: 'MINOTAUR', name: 'MINOTAUR', decimals: 9, chain: 'ton' },
  { address: 'EQAdFbynSUlzIlh_I4fXuYaer3rvY0TG0BK-NQZ-Y871pZoM', symbol: 'MIXER', name: '$TON Mixer', decimals: 9, chain: 'ton' },
  { address: 'EQDvLTIrlvsJzVERMDfx-64K_iht8dejr_OFY7Ea-Z5mGqrF', symbol: 'MMM', name: 'Mr. MeMe', decimals: 9, chain: 'ton' },
  { address: 'EQCH44N73BXEhT8063KAK_27oComvJnmAaebso-dZoyAy6g_', symbol: 'MMM', name: 'MMM2049', decimals: 9, chain: 'ton' },
  { address: 'EQCyfdVbfwkcBfBSn57GRnMY_BRO4vYG7HnkWngH41FLM-5Y', symbol: 'MMT', name: 'Making Money TON', decimals: 9, chain: 'ton' },
  { address: 'EQAmg7B4yk9H0blc4Z5clY-k9FbHzyUzWzzBD0VhXvv60uP_', symbol: 'MOKL', name: 'Mortal Klicker', decimals: 9, chain: 'ton' },
  { address: 'EQCymLRXp1QYxZKek4CTInckB1ey5TkyAJQpPAlNetiO54Vt', symbol: 'MRDN', name: 'Meridian', decimals: 9, chain: 'ton' },
  { address: 'EQCXIHAWDAJEJhMiNVqeUvp3I6O7y_P2sD80zEsJXeUi56mb', symbol: 'MUMBA', name: 'Mumba', decimals: 9, chain: 'ton' },
  { address: 'EQCFVNlRb-NHHDQfv3Q9xvDXBLJlay855_xREsq5ZDX6KN-w', symbol: 'MY', name: 'MyTonWallet Coin', decimals: 9, chain: 'ton' },
  { address: 'EQCgW3iMiYqkqBjqYR391w525-3pnFzVstHlbZ4dkulW_oz5', symbol: 'MiD', name: 'MiDtoken', decimals: 9, chain: 'ton' },
  { address: 'EQByn5rWMo254atRkD8DKHckK2FUIPYsEsU6osoyIK6M6Wt0', symbol: 'MineX', name: 'MineX', decimals: 9, chain: 'ton' },
  { address: 'EQBwy-wJ-wCqh0mfJHoWjmulJ0oIRKEJJt75ULyrJNPcnn5z', symbol: 'Mittens', name: 'Telegram\'s Cat', decimals: 9, chain: 'ton' },
  { address: 'EQD9zg_jMBEjQCwKln1xOO4iaf6F4r4R6YgXWPqIeWKqrTqj', symbol: 'NC', name: 'Nuka Cola', decimals: 9, chain: 'ton' },
  { address: 'EQBtzN5n9NkWGjO6uMlhN7F8UdwiY-CFodPuip0x5DUOG7K4', symbol: 'NEDO', name: 'Neo Dog', decimals: 9, chain: 'ton' },
  { address: 'EQATpT6zc9MrWnkjijj9rF0fyRT51WxsXAeBk9AQN2eRk4Nv', symbol: 'NEO', name: 'The Matrix', decimals: 9, chain: 'ton' },
  { address: 'EQDKE_OK-qkfyU08JbMFkiX5EtxXzF06j3XnJ-4jMJ8oGRyz', symbol: 'NEWS', name: 'Blockton News', decimals: 9, chain: 'ton' },
  { address: 'EQDo8QC6mVi7Gq6uGWDF4XVp3cZ4wKZ-bqKBkmhVMPm-1ojm', symbol: 'NIKO', name: 'NikolAI', decimals: 9, chain: 'ton' },
  { address: 'EQAvlWFDxGF2lXm67y4yzC17wYKD9A0guwPkMs1gOsM__NOT', symbol: 'NOT', name: 'Notcoin', decimals: 9, chain: 'ton' },
  { address: 'EQBygwrEcGIj5zmEtWeMGsQXbXr1WBgV3coVfqyURQighw2Y', symbol: 'NUDES', name: 'NUDES Coin', decimals: 9, chain: 'ton' },
  { address: 'EQC5zvSRzDAtL-kou3HpyVbOV_w-202wJi6Y0DwAM7GKmfCY', symbol: 'NUT', name: 'NUTCOIN', decimals: 9, chain: 'ton' },
  { address: 'EQAYxaCpAVHjpCWaZtrClXkOm9Yq7AVP2URAcRBW4GjtxOMj', symbol: 'OGAT', name: 'OGToken', decimals: 9, chain: 'ton' },
  { address: 'EQBMsJA42Q2ttxwRSgryHMT6vYpvkQ2VE-1pHkMQvq7VNXUU', symbol: 'ONLYX', name: 'OnlyX', decimals: 9, chain: 'ton' },
  { address: 'EQB0apV-NyCYJDVwSBoDL86Xjp0OiwcyD8jJ0J5BVWnnDJu7', symbol: 'OPEN', name: 'OPEN', decimals: 9, chain: 'ton' },
  { address: 'EQDf84FT8tdHZeI2-LXdb8gPMRqHRSABrmi8jI7MzvVpGJKZ', symbol: 'OPEN', name: 'OpenCoin', decimals: 5, chain: 'ton' },
  { address: 'EQCJLFpI0QR1QA_CYQ77Zm1_n85RDM4yLS46voZGRWbu9sbX', symbol: 'OR', name: 'Dog or Flower', decimals: 9, chain: 'ton' },
  { address: 'EQDQ2oBzTO4Itn9mmu3TL1v5TUiPS9PuAIVEq1xMpLHeeEsI', symbol: 'Only one token', name: 'Nano', decimals: 9, chain: 'ton' },
  { address: 'EQAj18Ki4sG47AXb14No35FnrMNBxC2uHcuIejJDyrd6VXpQ', symbol: 'PC', name: 'PAPA CARLO', decimals: 9, chain: 'ton' },
  { address: 'EQCm-KzJ6kacK9lhrnOaHR-W1KJGm-H415bEgsI04IVTDM57', symbol: 'PDFB', name: 'PDF Miner Boost', decimals: 9, chain: 'ton' },
  { address: 'EQBGtsm26tdn6bRjZrmLZkZMqk-K8wd4R66k52ntPU4UzcV0', symbol: 'PEDRO', name: 'PEDRO', decimals: 9, chain: 'ton' },
  { address: 'EQDPdNEYKpn26W-fgNVt6nyMgt3FFeEQmQwtcAFGxnhs1pUh', symbol: 'PEPE', name: 'TonPepe', decimals: 9, chain: 'ton' },
  { address: 'EQCXzO7HhoK5fDQuCONE43l8-Qsreq5zq89ZVNhEna24eK-h', symbol: 'PEPE', name: 'PEPE TON', decimals: 9, chain: 'ton' },
  { address: 'EQCJdxO9ZaV6orHd4osXIxWiV6tmDAuZaqSiOLKcr2u5fkjc', symbol: 'PEPE.MP3', name: 'PEPE.MP3', decimals: 9, chain: 'ton' },
  { address: 'EQBJOJ2eL_CUFT_0r9meoqjKUwRttC_-NUJyvWQxszVWe1WY', symbol: 'PET', name: 'Petcoin', decimals: 9, chain: 'ton' },
  { address: 'EQAi6vV3FYvPhQnYM-gxlRWXEpKZ8VM9p1v9eopK0Mc-89aS', symbol: 'PETA', name: 'Petachi', decimals: 9, chain: 'ton' },
  { address: 'EQBiNGBjmUjoSb8sIRGGN-wFe-f4ECiQZ2VGg_oApBTPwdpH', symbol: 'PETON', name: 'PEPETON', decimals: 9, chain: 'ton' },
  { address: 'EQCYRHQTqqEyHTYRH6zwwWl5wA7SBPhU5AdgMsI_qzp3JbQ5', symbol: 'PHOTON', name: 'PHOTON', decimals: 9, chain: 'ton' },
  { address: 'EQC-Gy-cWhXKNSeceUse-S9_FaTK--UIDkFED6cl5WpLASd6', symbol: 'PIECE', name: 'ONE', decimals: 18, chain: 'ton' },
  { address: 'EQCRWpQQmfSglpLp6D5Xebix50AStBxjfQQNkssFP_IsiQc3', symbol: 'PINGO', name: 'PinGo', decimals: 9, chain: 'ton' },
  { address: 'EQCgFCvZCV6qqB-2Kel6D_kV4zEW4FFOQfYV4KDDNTEJdItn', symbol: 'PIXEL', name: 'BORIS PIXEL', decimals: 9, chain: 'ton' },
  { address: 'EQDoqIKkOevVZukmf1L8nGhcjlha4sfvgl8GIRpTj_b53HyR', symbol: 'PIZZA', name: 'Pizza Gram', decimals: 9, chain: 'ton' },
  { address: 'EQAX9J60va-0wIDMdqGLRMf7imJvG0Ytyi3Yxnq9y-nbNCq2', symbol: 'PLANE', name: 'Paper Plane', decimals: 9, chain: 'ton' },
  { address: 'EQATgD7dao9jWBdz_qKL-UJZCXZGQvV5HJVUC85ssgmHKWll', symbol: 'PLANKTON', name: 'Plankton', decimals: 9, chain: 'ton' },
  { address: 'EQBB7RWO0qzo6JhikXLjmKJc81IS4JR0cyc5bPAL_h0GGmxW', symbol: 'POE', name: 'Portal Network Token', decimals: 9, chain: 'ton' },
  { address: 'EQC2YBaT9igu0hLnz1pPXqImVcJzdz0JWkqn5BTRf2A9h8Yl', symbol: 'POGO', name: 'Pogo', decimals: 9, chain: 'ton' },
  { address: 'EQBp6FAkDdHD_lLKUBI-J-Et5zQeyJlixc6f3iKHBie85Fd-', symbol: 'POK', name: 'Proof of Karl', decimals: 9, chain: 'ton' },
  { address: 'EQC8XkUEWb6bzbzE9eVaASoKUCyYA_CUQALGE15jWInEqla6', symbol: 'PONKE', name: 'PONKE TON', decimals: 9, chain: 'ton' },
  { address: 'EQCpildNt2xSlYHQy9_gmScHKDYtJTPwQokWt7jw1RnY0nzX', symbol: 'POST', name: 'POSTAL', decimals: 9, chain: 'ton' },
  { address: 'EQDoziSttQZ96QJRxHRKdatCm5L9DRL9LKycXcjl8RPXZM0N', symbol: 'POT', name: 'POT', decimals: 9, chain: 'ton' },
  { address: 'EQB1k0lxN7RSuDjJXajwypkkvMeyf6lIH8qRc7BQyDK62bld', symbol: 'POUCHI', name: 'POUCHI', decimals: 9, chain: 'ton' },
  { address: 'EQAzkUYcaP-JzcDeQTzMxuH3ptWhRN4yvp4xPu_cbpuE12YC', symbol: 'PPP', name: 'Player Pump Player', decimals: 9, chain: 'ton' },
  { address: 'EQDgSR_-4FDlXPfMVefXX1IIXMWBH4YfYV1a_8cJ0XsGVdsf', symbol: 'PROTON', name: 'PROTON JETTON', decimals: 9, chain: 'ton' },
  { address: 'EQC_oltAPJdQcykAf6PuKBbHtTXVSF8CCYdqhX6h-mmwGv59', symbol: 'PRRR', name: 'cats are liquidity', decimals: 9, chain: 'ton' },
  { address: 'EQAgotSkX06MIW-A0ni5yKqeNlwc3nASnbO1dwGo-kwpg2Zg', symbol: 'PTJ', name: 'PizzaTon Token', decimals: 9, chain: 'ton' },
  { address: 'EQCR03q7xmvx5bYPsZKrkSRJ23W-MpVl_FNP1W5rhqrxXrpP', symbol: 'PUMP', name: 'Pump&Dump', decimals: 9, chain: 'ton' },
  { address: 'EQBsTwY-0y5e1i6eVLklvkLwS2QJMllwWP7c4uq0ni6qxAvE', symbol: 'PUMPCORN', name: 'PUMPCORN', decimals: 9, chain: 'ton' },
  { address: 'EQAhPcpyfkhv2MPUxYm37g-NjZpBrp-hO-XEpOVkgOLAE2hS', symbol: 'PUN', name: 'Pun Dog', decimals: 9, chain: 'ton' },
  { address: 'EQCdpz6QhJtDtm2s9-krV2ygl45Pwl-KJJCV1-XrP-Xuuxoq', symbol: 'PUNK', name: '$PUNK', decimals: 9, chain: 'ton' },
  { address: 'EQAM0LPCnSsv5mVgBqMCu70kvbxNrSthfhu_QgeUTnvgtD22', symbol: 'PUTON', name: 'Vladimir Puton', decimals: 9, chain: 'ton' },
  { address: 'EQB8T1ylyks0DFFkUUC2KeFlzXMm-xDjvv6wDDRXLr6jTPRz', symbol: 'PWJ', name: 'PugWifJet', decimals: 9, chain: 'ton' },
  { address: 'EQB420yQsZobGcy0VYDfSKHpG2QQlw-j1f_tPu1J488I__PX', symbol: 'PX', name: 'Not Pixel', decimals: 9, chain: 'ton' },
  { address: 'EQD6Z9DHc5Mx-8PI8I4BjGX0d2NhapaRAK12CgstweNoMint', symbol: 'Points', name: 'Mintless Points', decimals: 9, chain: 'ton' },
  { address: 'EQD5rGGgViI16nT5nL0auCwZlTPCbwCOIjNkIx1oLW12tFgo', symbol: 'Puten', name: 'Volodemer', decimals: 9, chain: 'ton' },
  { address: 'EQCJbp0kBpPwPoBG-U5C-cWfP_jnksvotGfArPF50Q9Qiv9h', symbol: 'RAFF', name: 'Ton Raffles Token', decimals: 9, chain: 'ton' },
  { address: 'EQCF9oYxo37xCGX1DShZEweaVGJe6Kucp0ztKO6vCsRANDOM', symbol: 'RANDOM', name: 'Random.tg', decimals: 9, chain: 'ton' },
  { address: 'EQDsvbmh_rHjpO-FX3pmtPutllynl0OKuqqR9c1RICibsN6l', symbol: 'RCT', name: 'Round Chicken Token', decimals: 9, chain: 'ton' },
  { address: 'EQBYk9Rp8jgFmxE6XIIOiPJSxObAwt6DdThRdTP7t3JQhcTz', symbol: 'REBA', name: 'Rebalancer', decimals: 9, chain: 'ton' },
  { address: 'EQA8yEg5Ootec9ddg4dILwemNgsuqdQHjKJjjQAIJrVkyd33', symbol: 'REBE', name: 'Resistance Bear', decimals: 9, chain: 'ton' },
  { address: 'EQDd8qkUI2x0mOvp_D05RtK2EjJ7uHMjBZ7dS48nlO8FOJYZ', symbol: 'REBRE', name: 'Resistance Brett', decimals: 9, chain: 'ton' },
  { address: 'EQBZ_cafPyDr5KUTs0aNxh0ZTDhkpEZONmLJA2SNGlLm4Cko', symbol: 'REDO', name: 'Resistance Dog', decimals: 9, chain: 'ton' },
  { address: 'EQCcYUWKhjGxwqtk_je9LW2V4RoFmbhOUR9e404Y6FQTEXHh', symbol: 'REGI', name: 'The Resistance Girl', decimals: 9, chain: 'ton' },
  { address: 'EQDQEsrlf5ALa7-Gpz2nDK6t332bcyQoP0BzHj2KKTrXYVYB', symbol: 'REKT', name: 'REKT', decimals: 9, chain: 'ton' },
  { address: 'EQBwJaB-51Efd1CraJskTAkx2NDZHf71ONWUlJl-KIGOzs4b', symbol: 'REMY', name: 'Telegram\'s Dog', decimals: 6, chain: 'ton' },
  { address: 'EQDhr-ilmHPVEk2omrfQW0S5XLbyFm0v2zdGWYCDdfv1ZtXs', symbol: 'RESIST', name: 'Resistance Tates', decimals: 9, chain: 'ton' },
  { address: 'EQBueCLazRtAqwz6IPSoyutLtDNda5K-AFcOpR7ipbGMHlWL', symbol: 'RETRUMP', name: 'Resistance Trump', decimals: 9, chain: 'ton' },
  { address: 'EQA6_hsN-J3MmLaoJPMUN-g2iN4fG7SHsTQDlpuJ7yJkCgyC', symbol: 'RIC', name: 'Rio Global Invest Club', decimals: 9, chain: 'ton' },
  { address: 'EQAhPUM4o8QFLoj9T6l2muUDPxF6aH3Neo0rvWZUxwbDk85t', symbol: 'RING', name: 'RING', decimals: 9, chain: 'ton' },
  { address: 'EQBdr5b7csZbXhDnQ5U364bpLylHfk8AWcug8TwhzCMVcvPA', symbol: 'ROSE', name: 'Rosecoin', decimals: 9, chain: 'ton' },
  { address: 'EQB8RNC7E-0uWcfSP68rk_RReN2JYKQ4nBLq1RsKpaVme0xx', symbol: 'ROTGAR', name: 'Rotgar', decimals: 9, chain: 'ton' },
  { address: 'EQCweXSZaX5k5xOtXLbGgfF8FY6Dbg6rNiPrd9d0f_-kDSHZ', symbol: 'RUBETON', name: 'RubeTON', decimals: 9, chain: 'ton' },
  { address: 'EQAZdK27EU6LUNxTsWlhu3aZLHS3q3rNBzpiBTlkNHFssH8c', symbol: 'RUGP', name: 'Rug Police', decimals: 9, chain: 'ton' },
  { address: 'EQAXUTLNVMa_Hbm_GX2NzxvtoOA_iJU2d5Tf0E715MY_RUGP', symbol: 'RUGP', name: 'RUG POLICE', decimals: 9, chain: 'ton' },
  { address: 'EQDzvs6ZhNDZMQMeKK2Inc8ymDpORl0H5hAfgtf3dXRbt7I7', symbol: 'RUGPULL', name: 'Rug Pull', decimals: 9, chain: 'ton' },
  { address: 'EQCz6YaaF4e-tHzw3oJI4ltJKXJC_1w7QwHktFUUUsLYKjHM', symbol: 'RUS', name: 'RusCoinMem', decimals: 9, chain: 'ton' },
  { address: 'EQB087W3GWe2FIJPgoyI30Mf5d1hNBfqLc2s7wFTJJsX6qY_', symbol: 'Ruslon', name: 'Ruslon Skamolovsky', decimals: 9, chain: 'ton' },
  { address: 'EQAQB8Ut4tnlOl54this4vZqkWTVISybPnx_XID9337WzVra', symbol: 'SAC', name: 'Save Ass Coin', decimals: 9, chain: 'ton' },
  { address: 'EQCTYw9CpKm-7iO_VC_7DsqkeK1Bze-u--MeZMofjQg8tEWc', symbol: 'SADMEOW', name: 'SAD MEOW', decimals: 9, chain: 'ton' },
  { address: 'EQCT1Avbn7wfkJ45CHRU1PcdYd7gCnW7Tq52hof2UHw3CVWw', symbol: 'SADWOOF', name: 'SAD WOOF', decimals: 9, chain: 'ton' },
  { address: 'EQBgLw3RLkELgOJUU1oHtHzwkoTdb4RgfT8IgTG6k_iLneEc', symbol: 'SAFET', name: 'SafemoonTon', decimals: 9, chain: 'ton' },
  { address: 'EQD7rlGEfvNUXYbEwT-Ll7SUD7LuGkubUeU-TQXsShMwXY0H', symbol: 'SAINT', name: 'Saintcoin', decimals: 7, chain: 'ton' },
  { address: 'EQAFTzNeHcyBwO8IPvvOpi6V_n4B6O5P5keLq2xE4s8j9w4c', symbol: 'SAIYAN', name: 'Saiyan', decimals: 9, chain: 'ton' },
  { address: 'EQCIIUm7dnBgmcrubDfFLZV52oe1F_HFdDZiMfer9riphpQo', symbol: 'SAKE', name: 'SAKE', decimals: 9, chain: 'ton' },
  { address: 'EQAty7cyLIjF7U-K0VgG_gcksTAKtILkbJCNjPYlZ85cCZAA', symbol: 'SAU', name: 'SAUD', decimals: 9, chain: 'ton' },
  { address: 'EQC52I3c2rmZpUav0LrU6q7wuXoTmhOInvaFhKjZ6QuC5tV5', symbol: 'SCAM', name: 'SCAM', decimals: 9, chain: 'ton' },
  { address: 'EQBMXKRTIgCYxqyBhBx33b1WdQtyCnOii7KNQl_Pw8Z7O909', symbol: 'SCAM', name: 'TON SCAM', decimals: 9, chain: 'ton' },
  { address: 'EQDbiql2Kr9tHTfeDRmr5sOHjNXFkhpm3pkwq6NrmOnIinlU', symbol: 'SCAR', name: 'Tony Tontana', decimals: 9, chain: 'ton' },
  { address: 'EQAtwmCISetV3ncZRb1QDiHcbSgfo-Y37-zPL6NhedGHGaTf', symbol: 'SEED', name: 'SEED', decimals: 9, chain: 'ton' },
  { address: 'EQAJZElrDTgkt0exICrVUQPjN19knWOniGsJC_AunyqfPA0w', symbol: 'SFMT', name: 'SafeMars', decimals: 9, chain: 'ton' },
  { address: 'EQD39LNnyg6uEQv5jqkF76F45VY4sszDqqz2N8KbL1QQ3XPr', symbol: 'SHEEP', name: 'BARASH', decimals: 9, chain: 'ton' },
  { address: 'EQDBrZm6Gkh8s3Y92NfUKh71ZwhKZmZw0IgE1j3e6ZAfuqbd', symbol: 'SHIC', name: 'SHIC Coin', decimals: 9, chain: 'ton' },
  { address: 'EQA1jvPqRx6bujYohDny43hwX8FZr3b6OYnI3t2jHd4TXSJs', symbol: 'SHIP', name: 'TON SHIP', decimals: 9, chain: 'ton' },
  { address: 'EQB4gPfG0YtoiJHCMTUuzxP9fKXy9nx6TFh-dcAltrnNpLNo', symbol: 'SHIT', name: 'Shitcoin', decimals: 9, chain: 'ton' },
  { address: 'EQAQAYqUr9IDiiMQKvXXHtLhT77WvbhH7VGhvPPJmBVF3O7y', symbol: 'SHIVA', name: 'SHIVA the cat on Ton', decimals: 9, chain: 'ton' },
  { address: 'EQBAPusDK0W_pEyS_dMKhRQCpfFx0szeDZhLQ0EBoo4qhhXk', symbol: 'SIC', name: 'Shark Invest Club', decimals: 9, chain: 'ton' },
  { address: 'EQBCyYiqkTjAt5GBnVXguXLQpgl0ae1wxJXYZ6AibRLyZdem', symbol: 'SIMPL', name: 'Simple Ton Coin', decimals: 9, chain: 'ton' },
  { address: 'EQDK3ReFkb6L3uE3GmMDJaxWby4PA_UYGClgFfJuXY52-TOK', symbol: 'SLOW', name: 'Slowpoke', decimals: 9, chain: 'ton' },
  { address: 'EQDxiBc5tH3rGL7xVthFz84SWFyFVQPGOmhHghrf1VA4LBTu', symbol: 'SLUT', name: 'SLUT', decimals: 9, chain: 'ton' },
  { address: 'EQBSVKw3FK2o_aFJyMbdddTDQKLgvobVIzLwx8o9TwoksuK-', symbol: 'SNG', name: 'Sushi\'n\'Girls', decimals: 9, chain: 'ton' },
  { address: 'EQARb2CYeCT73K-a_cWXycgbcWlleEx4fq4RCbZ7cWBtPN8s', symbol: 'SOCK', name: 'BOLTWIFSOCK', decimals: 9, chain: 'ton' },
  { address: 'EQCHrhcBGVVlre8ngBlxLtfte37OGsXeJSmFSmABL8x44QH2', symbol: 'SOFT', name: 'The Open SOFT', decimals: 9, chain: 'ton' },
  { address: 'EQCwe0g3cEFhsz4VK5nrtOZBkFeSISxhCVUqvON7Im__SOON', symbol: 'SOON', name: 'SOON', decimals: 9, chain: 'ton' },
  { address: 'EQDhUoC8vFkB8BCDOVrYHylnFeLA343csl8_KSnj4FP3wc0_', symbol: 'SORRY', name: 'Sorry Mate', decimals: 9, chain: 'ton' },
  { address: 'EQBB-EMREJkIHVYG5DPiklOhWPcsCaxjL9HKmgRvuGtz_1lu', symbol: 'SOX', name: 'Nobby Game', decimals: 9, chain: 'ton' },
  { address: 'EQACLXDwit01stiqK9FvYiJo15luVzfD5zU8uwDSq6JXxbP8', symbol: 'SP', name: 'Spintria', decimals: 8, chain: 'ton' },
  { address: 'EQDuSjfrRO8Spn9XAugblUgCw0sR5vcgmarA5MkIj3gAg2a1', symbol: 'SPR', name: 'SPeculatoR', decimals: 9, chain: 'ton' },
  { address: 'EQCtxbfa9bVXn7wsfK5V72fX1RFuc8kFDF7piMioWENgEBx5', symbol: 'SQD', name: 'SquidTG', decimals: 9, chain: 'ton' },
  { address: 'EQAu8oDM_dXMgQd1COjRnU6sYhmvm5RP32gyyL9R2Rv-8s70', symbol: 'SQRL', name: 'SquirellCoin', decimals: 9, chain: 'ton' },
  { address: 'EQCMTNFQdQ4W5x4B7IkAGgrxoZxdADjgbDXVAxVRtjvLUJw_', symbol: 'ST6', name: 'Shill Team 6', decimals: 9, chain: 'ton' },
  { address: 'EQBHcVEoIwZ22GifL7BtVTGkzJKLQoC-rmqV6_nj7SR-hL2P', symbol: 'STATHAM', name: 'Jason Statham', decimals: 9, chain: 'ton' },
  { address: 'EQD5ty5IxV3HECEY1bbbdd7rNNY-ZcA-pAIGQXyyRZRED9v3', symbol: 'STBL', name: 'Stable Metal', decimals: 9, chain: 'ton' },
  { address: 'EQDnmln7FzwtwNdjdfsxWE21WFqIMVxqF6s4L1f2v2dbKR6Q', symbol: 'STEX', name: 'StableEX Technologies', decimals: 9, chain: 'ton' },
  { address: 'EQBjMUhuZnLRu45LtJNixAmWH48IrB61qk1wVWJqZKuNdDvm', symbol: 'STL', name: 'Stellarium', decimals: 9, chain: 'ton' },
  { address: 'EQA2kCVNwVsil2EM2mB0SkXytxCqQjS4mttjDpnXmwG9T6bO', symbol: 'STON', name: 'STON', decimals: 9, chain: 'ton' },
  { address: 'EQBsosmcZrD6FHijA7qWGLw5wo_aH8UN435hi935jJ_STORM', symbol: 'STORM', name: 'STORM', decimals: 9, chain: 'ton' },
  { address: 'EQBg57HDLFd920lqfPTXvGMENLD2oSmtraT3RDefici8x17g', symbol: 'Shapka', name: 'Dog Wif Shapka', decimals: 9, chain: 'ton' },
  { address: 'EQCcae9Wtj6U276LJgJD91pqgwESQohWLoolYrlv8arhafRT', symbol: 'Shiba', name: 'Shiba Inu Ton', decimals: 9, chain: 'ton' },
  { address: 'EQC24zbmyONM-m3DeCCYQpDRiinGjOu2cCHevwUFGWvdotAQ', symbol: 'Spotty', name: 'Spotty', decimals: 9, chain: 'ton' },
  { address: 'EQDYIz3EJa1GPp78qEvG0ZjFJoSsBbSo2i-n00lb-h5D8HxT', symbol: 'TAC', name: 'Toned Ape Coin', decimals: 9, chain: 'ton' },
  { address: 'EQAY5Kc7SfnfiTksWAyOTJ7Eu5oHKwqZHdtzHavKJlH3wqah', symbol: 'TAGO', name: 'TAGO WOLF', decimals: 9, chain: 'ton' },
  { address: 'EQBzyesZ3p1WGNrggNSJi6JFK3vr0GhqJp4gxker9oujjcuv', symbol: 'TAKE', name: 'TonTake', decimals: 9, chain: 'ton' },
  { address: 'EQAEWNwdwZO1CcRPsRxMtR0Otn7_Gd_K1aBQsXlDmnXEIDfv', symbol: 'TAKEN', name: 'TAKEN', decimals: 9, chain: 'ton' },
  { address: 'EQD3r1oCVcarXV7yENw6PQC2Y7Yd29enyseEIlARRC4-HtAp', symbol: 'TAPS', name: 'TapSwapToken', decimals: 9, chain: 'ton' },
  { address: 'EQBH-lTgGoe6x-wBoZGbOSBdVjfImvLEA2bueS_JR3GBsqFb', symbol: 'TAU', name: 'Taurus', decimals: 9, chain: 'ton' },
  { address: 'EQB2BOcnkwsIsjqd-rbAm4bvrum3_MJKMSgp974g7-zIo5xv', symbol: 'TAX', name: 'TON Attack', decimals: 9, chain: 'ton' },
  { address: 'EQDOgzGqEaUykB4VYN0QW96rHjlcbV0nAyS8nmr8-CYa_avf', symbol: 'TBCC', name: 'TBCC COIN', decimals: 9, chain: 'ton' },
  { address: 'EQBA-eB6kNVH89ATz6CXjP1sdhfAdx_U6zy-foDuWVy85DdH', symbol: 'TBO', name: 'Ton Turbo', decimals: 9, chain: 'ton' },
  { address: 'EQDnNof1yihA_JtXc70AZJCgw5_b1hIKkJGcdBXS5K-p3S-_', symbol: 'TBT', name: 'Tonbet Token', decimals: 9, chain: 'ton' },
  { address: 'EQCRuK5XIrie_QbeREfvTJQzZ4tRsK8mLhZl-XXLfz9i5WX6', symbol: 'TBTC', name: 'TonBitcoin', decimals: 9, chain: 'ton' },
  { address: 'EQBtDmYgCKk3ecQ1x-j0CLZRnPYyaV7cB33ad036QN-HE2C7', symbol: 'TCAT', name: 'TON Cat', decimals: 9, chain: 'ton' },
  { address: 'EQAvwJyVoXIwo17Siv5tHe-bwXMet2fccPnEgMDFLyG0BKUV', symbol: 'TDARKELON', name: 'DARK ELON on Ton', decimals: 9, chain: 'ton' },
  { address: 'EQD4XTXWJewuNtnhKGTkZaP0wsLvQyNgkVXcPLW5zPTQdykb', symbol: 'TDOG', name: 'TDOG', decimals: 9, chain: 'ton' },
  { address: 'EQBHswfj9uCHd42Z5a2ukFsnEbzg3Z0Y8rII35HjleldT0BV', symbol: 'TDOV', name: 'Ton Durov', decimals: 9, chain: 'ton' },
  { address: 'EQCh031TpoRtdrxxr0KJUh8gnEkJbV3iNw9QK-daH0dU9HJV', symbol: 'TEKTON', name: 'Tektoniks', decimals: 9, chain: 'ton' },
  { address: 'EQCXGFXKTp961E0nHDzu6geSdcvm0kiYIGKtiZ77tm9LFBZC', symbol: 'TELEGREM', name: 'Telegrem', decimals: 9, chain: 'ton' },
  { address: 'EQA5VgTNp7MUWsUb1XrUHFMDAKWSDyAUKyvmRGBuKn74tChu', symbol: 'TETE', name: 'Pepe on Ton', decimals: 9, chain: 'ton' },
  { address: 'EQAQV_OfpIXyRTYv-W6D7F10ZHfdwmYtgMR05ugQw1XdyEBz', symbol: 'TFISH', name: 'Tfish', decimals: 9, chain: 'ton' },
  { address: 'EQC00nmWACsj83LpnFZA4r1wDHB4dnZdTnkI8NJku7jFxirg', symbol: 'TFOX', name: 'TFOX', decimals: 9, chain: 'ton' },
  { address: 'EQAGswOePSPwbSur7Wx621wyxziLPzE5HdjHkJygpnWDX0Wu', symbol: 'TFROG', name: 'TON FROG', decimals: 9, chain: 'ton' },
  { address: 'EQAunJ_g3aswhm4WKrVxLT3zUHoZtg1koB58w5zMQTFVMi64', symbol: 'TFT', name: 'Ton Farm Token', decimals: 9, chain: 'ton' },
  { address: 'EQBG-qW7oE11g4cuViMsyweeqELS7nS9czKgwwBtBrnp-MIh', symbol: 'TGCONF', name: 'TgConf', decimals: 9, chain: 'ton' },
  { address: 'EQB36OxpWhlKwUMBiF9hdDAghDNkEWBupPq-3i_5D6tkSVU7', symbol: 'TGH', name: 'TGHUNTER', decimals: 9, chain: 'ton' },
  { address: 'EQDOWOJjgg_o2iVFkNJ-C-SLIVVe7mHPYIQ9ZLE4vtRzHHFM', symbol: 'TGOT', name: 'Game of Ton', decimals: 9, chain: 'ton' },
  { address: 'EQDRlQ8en7A2zsTuF7SdDOxMlZ_wFw0E7Eow3u9c4pSoe4Tg', symbol: 'TGRAM', name: 'Tgram', decimals: 9, chain: 'ton' },
  { address: 'EQB2MznQGkJyLsebxufcl8-hT-dn4D304W_RezZRSpExoHg0', symbol: 'THAMSTER', name: 'TON HAMSTER', decimals: 9, chain: 'ton' },
  { address: 'EQDAGGxez9tTT_Kg5_D9cqxYvmNPGGP2xsH5ubjekesxN8x8', symbol: 'THANKS', name: 'THANK YOU! СПАСИБО! 谢谢 شكرا ¡GRACIAS! MERCI!', decimals: 9, chain: 'ton' },
  { address: 'EQCaXA23e6IRVs6yKqjKSl_FGXq1bnIt43UFtSFOGP4WU3d5', symbol: 'THNG', name: 'Things Regular Token', decimals: 9, chain: 'ton' },
  { address: 'EQCQt2efxaLMKmLFn8O04ZOs0bi6e6Us9hV3QhmZ07TJEeN-', symbol: 'THOP', name: 'TON HOP', decimals: 9, chain: 'ton' },
  { address: 'EQCktEmAsvYBn8DPS6lu4QfatjEJJRLwD94aDqb8Ss6etuaA', symbol: 'TIGER', name: 'TIGER', decimals: 9, chain: 'ton' },
  { address: 'EQDPBEgdyAKSuDL_2abVW-5qQS0X5BEmqe_4TwB0l-LJCLOA', symbol: 'TKG', name: 'TAP KING', decimals: 9, chain: 'ton' },
  { address: 'EQAjQBt5h8SzLugDGp-75IiePuddLU32FGR4H3F3zPSLw7oL', symbol: 'TLB500', name: 'TLB500 Index', decimals: 9, chain: 'ton' },
  { address: 'EQAUdgmzu96-mTaQFnEWLX7GTpWjwsJa0LvGeq_s86hcr1nh', symbol: 'TMAGA', name: 'Trump/Telegram Make America Great Again', decimals: 9, chain: 'ton' },
  { address: 'EQChffb43kDZf5UsUXs6QGZEsvDEkoM1CEVabf-oihoU4d5U', symbol: 'TMILK', name: 'Ton Milk', decimals: 9, chain: 'ton' },
  { address: 'EQB-ajMyi5-WKIgOHnbOGApfckUGbl6tDk3Qt8PKmb-xLAvp', symbol: 'TNX', name: 'TonexCoin', decimals: 9, chain: 'ton' },
  { address: 'EQAaGlxC31YlSxzK_9hG3ka6UN1G9hbhXJI3STtfURHhIvsu', symbol: 'TNY', name: 'TONY', decimals: 9, chain: 'ton' },
  { address: 'EQB0UVc5fG1GzFrlRQ_Z0D9QnbK2NJNDU9hnn_nqXh_nxhIT', symbol: 'TOC', name: 'TONnie Coleman', decimals: 9, chain: 'ton' },
  { address: 'EQA7nLJI-Eoc5oBzEBnlLzezTEwGNRvyR5tX7iWHT8KPwVy1', symbol: 'TON7DAO', name: 'TON7DAO', decimals: 9, chain: 'ton' },
  { address: 'EQCX_vSR8q0OSN74_BSq_ZieLZuNGx7wt0sXq1t5EI0q2SRI', symbol: 'TONALD', name: 'TONALD TRUMP', decimals: 9, chain: 'ton' },
  { address: 'EQDVkOpW-r6RiRYSpGRKnVvvf8YQkA-X9ZLZxtddaQldVzg6', symbol: 'TONCUP', name: 'Ton Cuphead', decimals: 9, chain: 'ton' },
  { address: 'EQC0KYVZpwR-dTkPwVRqagH2D31he931R7oUbPIBo_77F97K', symbol: 'TONG', name: '痛', decimals: 9, chain: 'ton' },
  { address: 'EQC4D-qkAaqYXWOnWRJx6xtOhd7Fa9zZQdob8iWD6mS_kPqU', symbol: 'TONIC', name: 'TONic', decimals: 18, chain: 'ton' },
  { address: 'EQDv68b3JaWBO_DrP6u13Oq7KsnKhR926kMxcOJwACDY_uQC', symbol: 'TONK', name: 'Tonk Inu', decimals: 9, chain: 'ton' },
  { address: 'EQCQlDd6eyUDlWP2NIUn2ZyGZ8ktg_HKXB288jv4Kp1Yflo6', symbol: 'TONKE', name: 'Tonke', decimals: 9, chain: 'ton' },
  { address: 'EQB7hdt89YNMoaCgs8ZiiD2aZRMr2ui5mopw2G_IoWhf0cY6', symbol: 'TONKOFF', name: 'Aleg Tonkoff', decimals: 9, chain: 'ton' },
  { address: 'EQC6wa8GBg9TxcwjGRYJbvuAqjPi1kFFe50-g0eGgBvxTCbe', symbol: 'TONKY', name: 'Tonkey', decimals: 9, chain: 'ton' },
  { address: 'EQDNDv54v_TEU5t26rFykylsdPQsv5nsSZaH_v7JSJPtMitv', symbol: 'TONNEL', name: 'Tonnel Network Token', decimals: 9, chain: 'ton' },
  { address: 'EQD7sIfP2PR8v7RjZxRk8fPymsjE3hUiYDDaAD38x6LCtG2f', symbol: 'TONNY', name: 'TONNY', decimals: 9, chain: 'ton' },
  { address: 'EQCzx9Q7ckKZXkyTZsCnTXxQKbr-l06-qz9wrXWWeNzlwO09', symbol: 'TONR', name: 'TON RENAISSANCE', decimals: 9, chain: 'ton' },
  { address: 'EQBiJd6z0WiuiCQdywPOqaLyT2TbTfV79Pzu9K1R3l_qlUZ5', symbol: 'TONY', name: 'TONY THE DUCK', decimals: 9, chain: 'ton' },
  { address: 'EQAO3n9xmdXwXHUhtZ3zKexpeUEKejYVKCeEupdsg2kvgcof', symbol: 'TOON', name: 'ToonTools', decimals: 9, chain: 'ton' },
  { address: 'EQBJBF7FKCRE6ClTG3NNUlWejM4Gaewa__vgFaBjJHoIDeuu', symbol: 'TOSHKA', name: 'TOSHKA', decimals: 9, chain: 'ton' },
  { address: 'EQAcjv-v76upZgRoRNUM6tCmd6d9Q09sWVTFqCdfLeuP4P3b', symbol: 'TOT', name: 'TonTogether', decimals: 9, chain: 'ton' },
  { address: 'EQDs9X4xZtBe9Z6kr8Mbmgm-yQtid4aiQl64Ra3KryGX8kOQ', symbol: 'TOTO', name: 'Toto the Wizard Toad', decimals: 9, chain: 'ton' },
  { address: 'EQAmQGimKRrSHDLllvdUdeDsX1CszGy_SPgNNN8wE2ihIwnP', symbol: 'TPET', name: 'TON PET MEMECOIN', decimals: 9, chain: 'ton' },
  { address: 'EQB16viG6sJi3rRarA7TheGjEBzi5pVlwIlc30fvN3mSJjdM', symbol: 'TREX', name: 'TON REX', decimals: 9, chain: 'ton' },
  { address: 'EQCcXKwYGCCZnzQj9vwwg8Y-F3d8H7cow-Mwgj8pTFruBfP8', symbol: 'TRIBE', name: 'Tribe', decimals: 2, chain: 'ton' },
  { address: 'EQBZGBxlhSpBzQfFdj7AqJa6tIavsCaFBYDl2C5J5TIFecrH', symbol: 'TRUMP', name: 'Ton Trump', decimals: 6, chain: 'ton' },
  { address: 'EQAlXsX5yXFtTPOSLEBCcdrWtyZvC48nBRrjyCcuCOgHyFFS', symbol: 'TRUMP3', name: 'Trump MP3', decimals: 9, chain: 'ton' },
  { address: 'EQC5fAP56z6iyTg1idj_mV1VBofi2KwJ1Hf8m2P0HphDgE10', symbol: 'TRUST', name: 'Trust', decimals: 9, chain: 'ton' },
  { address: 'EQC5DX3xP_jZETDDg3Ja_H2XgOHOGP1tPy98v6hhciUepv76', symbol: 'TSE', name: 'TONSEASON', decimals: 9, chain: 'ton' },
  { address: 'EQDlJ8mXEP__aFSO5BbMMDovMLtULZLfEmDbGkdYPVW_MYYJ', symbol: 'TSHIB', name: 'TON SHIBA', decimals: 9, chain: 'ton' },
  { address: 'EQAr6FVqQfktKsjhDhtk-sQnjXsOjehpf6Wr_TPozGbW4Dhx', symbol: 'TSP', name: 'TRANSPARENT', decimals: 9, chain: 'ton' },
  { address: 'EQAGYK08DaJaQpmZESz3y9gqi7rmpoBiyKQru-firOwqPzR4', symbol: 'TSWAP', name: 'TeleSwap', decimals: 9, chain: 'ton' },
  { address: 'EQDqrKJj1ZQeGTHSmjDkoe-1BrvKJ3tJzjWo-6y63lfvVU9R', symbol: 'TWIDO', name: 'Twister The Dog', decimals: 9, chain: 'ton' },
  { address: 'EQCLSw7jSAKIIUTSzwWK_AdJB4osJ3fF8nOHzfDJhP_KCZRR', symbol: 'TWRINV', name: 'Tower investors', decimals: 5, chain: 'ton' },
  { address: 'EQAb64zkvhg6biFzqkuGEXw_cI2z4Y1MmlJE0263pCuj5nU_', symbol: 'TYLER', name: 'TYLERCOIN', decimals: 9, chain: 'ton' },
  { address: 'EQB0U4TH69CBD6AeO_yHFMW-u90UmH_65Gw5AkZblt3GO4R6', symbol: 'TYS', name: 'Tvorog', decimals: 9, chain: 'ton' },
  { address: 'EQDOrlRmgxBVo9I2Ijc7zhlm_jAhJR27YA_LeDoQsw4N0yFD', symbol: 'Token 69', name: 'Token 69', decimals: 9, chain: 'ton' },
  { address: 'EQAWy9ddqQJgwtCR-H4QsPOIcZsr55O-O6eI4sZj28dWzgLA', symbol: 'TonDoge', name: 'Ton Doge Coin', decimals: 9, chain: 'ton' },
  { address: 'EQB2lbt2s_jdUW3OoUIb7-9RoK2UeGXmgC7BnOwgK6P_JTrm', symbol: 'UNIC', name: 'UNICORN', decimals: 9, chain: 'ton' },
  { address: 'EQDNda_XHyRGE__pPRae0QiIWmAvVjf5mCPn0fQWHktIbiyl', symbol: 'UNK', name: 'Unknown coin', decimals: 9, chain: 'ton' },
  { address: 'EQCvaf0JMrv6BOvPpAgee08uQM_uRpUd__fhA7Nm8twzvbE_', symbol: 'UP', name: 'TonUP', decimals: 9, chain: 'ton' },
  { address: 'EQDjeocqoV44Y3miqstuQ0cT5BxSV05E2qEV2VY1OXRQJGGB', symbol: 'USACH', name: 'Us Usach', decimals: 9, chain: 'ton' },
  { address: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', symbol: 'USDT', name: 'Tether USD', decimals: 6, chain: 'ton' },
  { address: 'EQDIOMTzweGCrV6KvQFfbgKkc2QL7h_5m0MABWGDD0rR4zji', symbol: 'USDT TON', name: 'Tether TON', decimals: 6, chain: 'ton' },
  { address: 'EQAIb6KmdfdDR7CN1GBqVJuP25iCnLKCvBlJ07Evuu2dzP5f', symbol: 'USDe', name: 'Ethena USDe', decimals: 6, chain: 'ton' },
  { address: 'EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs', symbol: 'USD₮', name: 'Tether USD', decimals: 6, chain: 'ton' },
  { address: 'EQBaCgUwOoc6gHCNln_oJzb0mVs79YG7wYoavh-o1ItaneLA', symbol: 'UTYA', name: 'Utya', decimals: 9, chain: 'ton' },
  { address: 'EQBh9XACT0B60U8Q48VnjyqCxzxpM4oA0c8rqKt4h70yk1V5', symbol: 'UXLINK', name: 'UXLINK Token', decimals: 9, chain: 'ton' },
  { address: 'EQDqQscohYilSqWEyeLyCReOQKOh7KhRX_CPlD-Qdx02tUbG', symbol: 'VC', name: 'Vincere', decimals: 9, chain: 'ton' },
  { address: 'EQBJEVOot-Jcz6bj45hUVNRHhHZDtuF7ts5ZJIgjW_tlBq7d', symbol: 'VILARSO', name: 'Vilarso', decimals: 9, chain: 'ton' },
  { address: 'EQD0mixtftw76FUcV0Nl0oQmCPbJ86DULGNb42A1POxZCk3U', symbol: 'VIP', name: 'VIP Coin', decimals: 9, chain: 'ton' },
  { address: 'EQC7zE2BVcLiybBMuQ1giOPYmO4Ji88J12r7duqMJWOtFxtr', symbol: 'VIRUS', name: 'Epidemy', decimals: 9, chain: 'ton' },
  { address: 'EQBfX9KO5yIFprHWPpJp3OsX-6cjLjEJF-h5uIQE3eLJY8_h', symbol: 'VWS', name: 'Virtuals Worlds', decimals: 18, chain: 'ton' },
  { address: 'EQAQElB3trMwj0wCnVVYYFnJrbpwCO_NXDaTuj9aYigLovXw', symbol: 'WAKEUP', name: 'Wakeup DAO Token', decimals: 9, chain: 'ton' },
  { address: 'EQDdCha_K-Z97lKl599O0GDAt0py2ZUuons4Wuf85tq6NXIO', symbol: 'WALL', name: 'Du Rove\'s Wall', decimals: 9, chain: 'ton' },
  { address: 'EQCEqz2x3-Ub_EO4Y5798NNoqKw1tP_tJ6b9y-X0C4uvs8Zf', symbol: 'WAT', name: 'WATCoin', decimals: 9, chain: 'ton' },
  { address: 'EQBrvab8EuKoP4S9XZMAwpq58PfT_UJw74JTdqqBS2UEygUh', symbol: 'WBR', name: 'Will be rich', decimals: 9, chain: 'ton' },
  { address: 'EQDB0bjWnVFjx6gtTAPVMdp6mdooS5xpjhBoJO2OQ6Qf0vt9', symbol: 'WD', name: 'WORK DOGS', decimals: 9, chain: 'ton' },
  { address: 'EQBtcL4JA-PdPiUkB8utHcqdaftmUSTqdL8Z1EeXePLti_nK', symbol: 'WEB3', name: 'Web3 TON Token', decimals: 3, chain: 'ton' },
  { address: 'EQA3LxaRQBzZ_QzPsx16EAJ_AchJl0wt4r33Jf0NBofSmOY8', symbol: 'WEED', name: 'WEED on TON', decimals: 9, chain: 'ton' },
  { address: 'EQCfEsiSMI-9mEVqFvA1A3xn7q4DFYYc_RqyZQjveID_eG2I', symbol: 'WEED', name: 'Weed coin - cannabis meme coin on TON', decimals: 9, chain: 'ton' },
  { address: 'EQBeruz-RXKQFsVHh6busCylN3_VyeZ2KLyC4hiulg-nQVfj', symbol: 'WEND', name: 'WEN DIZEL', decimals: 9, chain: 'ton' },
  { address: 'EQCObh4-ZaghOva8uCz_AMMnvifM3PS-EppUJEJQXXnlP0zX', symbol: 'WHISK', name: 'Whiskers', decimals: 9, chain: 'ton' },
  { address: 'EQAuco5ZEPgB19fSTo7EmtLTJysrKxbu6M_XOFDwWQiNjCsQ', symbol: 'WIF', name: 'DOGWIFHOOD', decimals: 9, chain: 'ton' },
  { address: 'EQA7cfcPCpFh2o3ZH6EkxBck_SdbLH_scAEbHXKxamlfSvGH', symbol: 'WOJAK', name: 'Wojak on TON', decimals: 9, chain: 'ton' },
  { address: 'EQDmj_i7VMXstzF9dTgQMyPKyvQIynYD0KJ7pI8v1LU400Rh', symbol: 'WON', name: 'Wonnie', decimals: 9, chain: 'ton' },
  { address: 'EQBKyWOOFXlJpzYO8e44JG6uf6L3v4bYbbBBnKj9OHwBXjzm', symbol: 'WOOF', name: 'WOOF', decimals: 9, chain: 'ton' },
  { address: 'EQDAVeTzJhaSHVKfeRLytMmQ6nE8C5ZRc-ky_81ThQ2AFmo9', symbol: 'WOOSH', name: 'woosh', decimals: 9, chain: 'ton' },
  { address: 'EQBh4srSjynQxa1XkZPQZcNDGS1BuWURtIQsomqYd2vX7oll', symbol: 'WUF', name: 'Wuffi', decimals: 4, chain: 'ton' },
  { address: 'EQB4zZusHsbU2vVTPqjhlokIOoiZhEdCMT703CWEzhTOo__X', symbol: 'X', name: 'X Empire', decimals: 9, chain: 'ton' },
  { address: 'EQD7THgw9GZ7udZzjzwiBXMHEKSCHiElKEHjn_-lcXoGApel', symbol: 'XCM', name: 'xCryproMarket', decimals: 9, chain: 'ton' },
  { address: 'EQAl-wAQ5RzBMvWyI9cU1pDA51kE9C5KD842DVXZHvF9ygFz', symbol: 'XPBEAT', name: 'BEAT XP', decimals: 9, chain: 'ton' },
  { address: 'EQAVfEY2iKSpEkUhgFLFWAgHeSz2NH2XV-MvDuiKF5plSbsU', symbol: 'XROCK', name: 'xRocket Token', decimals: 9, chain: 'ton' },
  { address: 'EQCL6jaTluAI7ET_JgZ3hPV9Ul8MXP2mZWhMQtGMzd-cNt-X', symbol: 'Y', name: 'Ptah', decimals: 9, chain: 'ton' },
  { address: 'EQDzcpYY0c5iyNLha15iGHRvSvlC3Y4C9g5BILouzVaM7OPL', symbol: 'YAN', name: 'CryptoYan Universe', decimals: 9, chain: 'ton' },
  { address: 'EQCDkrpCu-FFVPQJnManjlf8XCN75wjX_AKrrEFFQ1mfJqZo', symbol: 'YO', name: 'Yoken', decimals: 9, chain: 'ton' },
  { address: 'EQBRmwuHXat8BiOgkkarCk7HucRBjcyOb8efwOuT45Cectl5', symbol: 'YOBA', name: 'Meme Inc', decimals: 9, chain: 'ton' },
  { address: 'EQA0tQ880E68-ZGsugW3kjm5hk_5hUAWTdVggFlJmqqVQgCm', symbol: 'YUME', name: 'Vladimir Putin\'s Dog', decimals: 9, chain: 'ton' },
  { address: 'EQC7vuKEYLdC72YhUWt3AUVA-Oi66Q1DxTHXH7r6pXaV50j7', symbol: 'Yoda', name: 'Baby Yoda', decimals: 9, chain: 'ton' },
  { address: 'EQC9DbBKEi6gbzn85XENDDTlu9mWRLMB8cBlm31F80c0dvba', symbol: 'ZEN', name: 'Zencoin', decimals: 9, chain: 'ton' },
  { address: 'EQCTUG05xJSNRFhAza1M9UjKkXqawGcSlxWHTCqM5F0MEWKN', symbol: 'ZEUS', name: 'ZEUS', decimals: 9, chain: 'ton' },
  { address: 'EQAjWFZaH0Xib0VGEwe3148Hg7arST5mhJwDB3YTIS0OFUxJ', symbol: 'aPine', name: 'Antique Pine', decimals: 9, chain: 'ton' },
  { address: 'EQCSxGZPHqa3TtnODgMan8CEM0jf6HpY-uon_NMeFgjKqkEY', symbol: 'bmTON', name: 'Bemo', decimals: 9, chain: 'ton' },
  { address: 'EQAl0ChJyynGWg0tGMCBM6soeKJrKtNm_IATf17jcFEQx0Ww', symbol: 'durev', name: 'povel durev', decimals: 9, chain: 'ton' },
  { address: 'EQB02DJ0cdUD4iQDRbBv4aYG3htePHBRK1tGeRtCnatescK0', symbol: 'durev', name: 'povel durev', decimals: 9, chain: 'ton' },
  { address: 'EQDPdq8xjAhytYqfGSX8KcFWIReCufsB9Wdg0pLlYSO_h76w', symbol: 'hTON', name: 'Hipo Staked TON', decimals: 9, chain: 'ton' },
  { address: 'EQDOrg1GXObvpLoQSpnGxcb5wA42-V2CcFl6Pr25sVoJVmTv', symbol: 'hmm', name: 'Hmmcoin', decimals: 9, chain: 'ton' },
  { address: 'EQDsrCYtZgbO57PQ47b9oytjQrUjix-gz2wIP088DEUvh2kC', symbol: 'jARBUZ', name: 'ARBUZ', decimals: 18, chain: 'ton' },
  { address: 'EQCbkRdpnrWZfm07dP5n_wjGx6llNkHNIdmZ-gpIQcDP-J-5', symbol: 'jBTC', name: 'jBTC', decimals: 9, chain: 'ton' },
  { address: 'EQCb1SAX1heK9tK8a5CXtYSbdHXkPPAXWKTy3Yz5PH1lglIu', symbol: 'jETH', name: 'jETH', decimals: 9, chain: 'ton' },
  { address: 'EQAEuikLQVh2lDMrV99nTHqFL_TXEyCEJ1xKMuPT60tfvdps', symbol: 'jMNT', name: 'Mantle', decimals: 18, chain: 'ton' },
  { address: 'EQAWsIGMoGlbjJJIsik-9_6A4Iiodb1M7LW3kmu05v8ujo9h', symbol: 'jMOEW', name: 'donotfomoew', decimals: 18, chain: 'ton' },
  { address: 'EQCOGp1GAVk51prVBw5DO8QN3lKIlUJKjXbZcl5aXgL5hkwy', symbol: 'jNANO', name: 'Wrapped NANO', decimals: 9, chain: 'ton' },
  { address: 'EQDu9ijk44grAHe3Dy9qYOy-hic-vJr4d1CH3HNyN-gT5LyL', symbol: 'jTIME', name: 'ChronoTech Token', decimals: 8, chain: 'ton' },
  { address: 'EQB-MPwrd1G6WKNkLz_VnV6WqBDd142KMQv-g1O-8QUA3728', symbol: 'jUSDC', name: 'jUSDC', decimals: 6, chain: 'ton' },
  { address: 'EQBynBO23ywHy_CgarY9NK9FTz0yDsG82PtcbSTQgGoXwiuA', symbol: 'jUSDT', name: 'jUSDT', decimals: 6, chain: 'ton' },
  { address: 'EQDcBkGHmC4pTf34x3Gm05XvepO5w60DNxZ-XT4I6-UGG5L5', symbol: 'jWBTC', name: 'jWBTC', decimals: 8, chain: 'ton' },
  { address: 'EQCCu_XUzID_mtU-z262JJwvurqPiiUsurLst1uc5mlwNQJl', symbol: 'nyetcat', name: 'no cat', decimals: 9, chain: 'ton' },
  { address: 'EQC_1YoM8RBixN95lz7odcF3Vrkc_N8Ne7gQi7Abtlet_Efi', symbol: 'oUSDT', name: 'Orbit Bridge Ton USD Tether', decimals: 6, chain: 'ton' },
  { address: 'EQDNhy-nxYFgUqzfUzImBEP67JqsyMIcyk2S5_RwNNEYku0k', symbol: 'stTON', name: 'Staked TON', decimals: 9, chain: 'ton' },
  { address: 'EQAORkhhrXis_XxLAAfyxTyNceNXLtaHcJ5FhXxpNJ8xsDGc', symbol: 'stXP', name: 'bemo Staking Experience Point', decimals: 9, chain: 'ton' },
  { address: 'EQC98_qAmNEptUtPc7W6xdHh_ZHrBUFpw5Ft_IzNU20QAJav', symbol: 'tsTON', name: 'Tonstakers TON', decimals: 9, chain: 'ton' },
  { address: 'EQDQ5UUyPHrLcQJlPAczd_fjxn8SLrlNQwolBznxCdSlfQwr', symbol: 'tsUSDe', name: 'Ethena tsUSDe', decimals: 6, chain: 'ton' },
  { address: 'EQBVLRoaw1F8VEBE_AG5K2BXaXki0nKPnvf70CAqGy6tu22X', symbol: 'tun', name: 'teh upen netwerg', decimals: 9, chain: 'ton' },
  { address: 'EQAfF5j3JMIpZlLmACv7Ub7RH7WmiVMuV4ivcgNYHvNnqHTz', symbol: 'uTON', name: 'uTON', decimals: 9, chain: 'ton' },
  { address: 'EQB0SoxuGDx5qjVt0P_bPICFeWdFLBmVopHhjgfs0q-wsTON', symbol: 'wsTON', name: 'Ton Whales liquid staking token', decimals: 9, chain: 'ton' },
  { address: 'EQDptzse--Atn4hDt2dGl3TxAN0Ak6taYXEiNKOg7EAibChH', symbol: 'Æ', name: 'Ærly🕊️Birds', decimals: 7, chain: 'ton' },
  { address: 'EQAa82rJAdAjpR5N7EunqpKSzdDkcCUCRbA37XQkvEq_ek6T', symbol: 'БОБО', name: 'Бобо медведь', decimals: 9, chain: 'ton' },
  { address: 'EQAjoDjgPC3ngpgMtHBS8a1tUKc4ULZJ5yVohnY75zk-Cdoi', symbol: 'ВОЛК', name: 'ВОЛК', decimals: 9, chain: 'ton' },
  { address: 'EQCpCIOM55On1ht_uKzXDXONxVjBD1YqMOIhHq6eh-oCN70d', symbol: 'Зайчик', name: 'Зайчик', decimals: 9, chain: 'ton' },
  { address: 'EQCVfCoiD1IhsQKaVwp7xoAHAGw4aEAp7dE4VjDsCV_8hrIR', symbol: 'Шайлушай', name: 'Шайлушай', decimals: 9, chain: 'ton' },
  { address: 'EQDa5-yO3m0PoiuAaDtRuNm_M_nUMkA1X3p9cwKXjk266NL7', symbol: 'Шапокляк', name: 'Шапокляк', decimals: 9, chain: 'ton' },
  { address: 'EQCHI8fqIY9jMIguQTJPjm8_H_ZBIZ2cnV8x4lgGc5e4mOCb', symbol: 'матроскин', name: 'Кот Матроскин', decimals: 9, chain: 'ton' },
  { address: 'EQCQVzfQNyaMF3EI6u0Zt7UWct6u6QVF3n-nPUBu0HqpedY-', symbol: 'матрёшка', name: 'матрёшка', decimals: 9, chain: 'ton' },
  { address: 'EQABxFYjGY4quYR2wSSltiY7mf9LANIirtk_u_-I9eiCRiry', symbol: 'чебурашка', name: 'чебурашка', decimals: 9, chain: 'ton' },
];

const KNOWN_MAP: Record<string, { symbol: string; name: string; decimals: number }> = {};
for (const t of KNOWN_TOKENS) KNOWN_MAP[t.address] = t;

// GET /addresses/:address/tokens
router.get('/', async (req: Request, res: Response) => {
  try {
    const ctx = resolveOr400(req, res);
    if (!ctx) return;
    const address = ctx.address;
    const chain = ctx.chain;
    const network = (req.query.network as string) || ctx.network;

    const cacheKey = `jettons:${address}:${chain}`;
    let cached = cache.get<object[]>(cacheKey);

    if (!cached) {
      if (chain === 'ton') {
        const { jetton_wallets, metadata } = await getJettonWallets(network, address);
        cached = jetton_wallets.map(jw => {
          const meta = metadata[jw.jetton] || {};
          const known = KNOWN_MAP[jw.jetton];
          const decimals = known?.decimals ?? parseInt(meta.decimals || '9', 10);
          const balance = formatAmount(jw.balance, decimals);
          return {
            jetton_master: jw.jetton,
            jetton_wallet: jw.address,
            symbol: known?.symbol || meta.symbol || '?',
            name: known?.name || meta.name || 'Unknown Token',
            decimals,
            balance_raw: jw.balance,
            balance,
            last_tx_lt: jw.last_transaction_lt,
          };
        }).filter(t => t.balance_raw !== '0');
      } else if (EVM_CHAINS.has(chain)) {
        const { tokens } = await evmGetBalance(chain, address);
        cached = tokens;
      } else if (chain === 'solana') {
        const { tokens } = await solanaGetBalance(address);
        cached = tokens;
      } else if (chain === 'tron') {
        const { tokens } = await tronGetBalance(address);
        cached = tokens;
      } else {
        cached = [];
      }

      cache.set(cacheKey, cached, TTL.JETTONS);
    }

    res.json({ count: cached.length, tokens: cached });
  } catch (err: unknown) {
    res.status(500).json({ error: String(err) });
  }
});

// GET /tokens/known
export function knownTokensHandler(_req: Request, res: Response): void {
  res.json({ count: KNOWN_TOKENS.length, tokens: KNOWN_TOKENS });
}

function formatAmount(raw: string, decimals: number): string {
  const n = BigInt(raw || '0');
  const factor = BigInt(10 ** decimals);
  const whole = n / factor;
  const frac = (n % factor).toString().padStart(decimals, '0').replace(/0+$/, '') || '0';
  return `${whole}.${frac}`;
}

export default router;
